oomph::RefineableQTaylorHoodSpaceTimeElement< DIM > Class Template Reference
Refineable version of Taylor Hood elements. These classes can be written in total generality.
#include <refineable_discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h>
Public Member Functions
RefineableQTaylorHoodSpaceTimeElement ()
Constructor.
unsigned required_nvalue (const unsigned &n) const
Number of values required at local node n. In order to simplify matters, we allocate storage for pressure variables at all the nodes and then pin those that are not used.
unsigned ncont_interpolated_values () const
Number of continuously interpolated values.
void rebuild_from_sons (Mesh *&mesh_pt)
Rebuild from sons: empty.
unsigned nrecovery_order ()
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
unsigned nvertex_node () const
Number of vertex nodes in the element.
Node * vertex_node_pt (const unsigned &j) const
Pointer to the j-th vertex node in the element.
void get_interpolated_values (const Vector< double > &s, Vector< double > &values)
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
void get_interpolated_values (const unsigned &t, const Vector< double > &s, Vector< double > &values)
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
void further_setup_hanging_nodes ()
Perform additional hanging node procedures for variables that are not interpolated by all nodes. The pressures are stored at the p_nodal_index_nst-th location in each node.
Node * pressure_node_pt (const unsigned &n_p)
Pointer to n_p-th pressure node.
Node * interpolating_node_pt (const unsigned &n, const int &value_id)
The velocities are isoparametric and so the "nodes" interpolating the velocities are the geometric nodes. The pressure "nodes" are a subset of the nodes, so when value_id==DIM, the n-th pressure node is returned.
double local_one_d_fraction_of_interpolating_node (const unsigned &n_1d, const unsigned &i, const int &value_id)
The pressure nodes are the corner nodes, so when n_value==DIM, the fraction is the same as the 1D node number, 0 or 1.
Node * get_interpolating_node_at_local_coordinate (const Vector< double > &s, const int &value_id)
The velocity nodes are the same as the geometric nodes. The pressure nodes must be calculated by using the same methods as the geometric nodes, but by recalling that there are only two pressure nodes per edge.
unsigned ninterpolating_node_1d (const int &value_id)
The number of 1D pressure nodes is 2, the number of 1D velocity nodes is the same as the number of 1D geometric nodes.
unsigned ninterpolating_node (const int &value_id)
The number of pressure nodes is 2^DIM. The number of velocity nodes is the same as the number of geometric nodes.
void interpolating_basis (const Vector< double > &s, Shape &psi, const int &value_id) const
The basis interpolating the pressure is given by pshape(). / The basis interpolating the velocity is shape().
void build_fp_press_adv_diff_robin_bc_element (const unsigned &face_index)
Build FaceElements that apply the Robin boundary condition to the pressure advection diffusion problem required by Fp preconditioner.
void identify_load_data (std::set< std::pair< Data *, unsigned > > &paired_load_data)
Add to the set paired_load_data pairs containing.
RefineableQTaylorHoodSpaceTimeElement ()
Constructor.
unsigned required_nvalue (const unsigned &n) const
Number of values required at local node n. In order to simplify matters, we allocate storage for pressure variables at all the nodes and then pin those that are not used.
unsigned ncont_interpolated_values () const
Number of continuously interpolated values.
void rebuild_from_sons (Mesh *&mesh_pt)
Rebuild from sons: empty.
unsigned nrecovery_order ()
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
unsigned nvertex_node () const
Number of vertex nodes in the element.
Node * vertex_node_pt (const unsigned &j) const
Pointer to the j-th vertex node in the element.
void get_interpolated_values (const Vector< double > &s, Vector< double > &values)
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
void get_interpolated_values (const unsigned &t, const Vector< double > &s, Vector< double > &values)
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
void further_setup_hanging_nodes ()
Perform additional hanging node procedures for variables that are not interpolated by all nodes. The pressures are stored at the p_nodal_index_nst-th location in each node.
Node * pressure_node_pt (const unsigned &n_p)
Pointer to n_p-th pressure node.
Node * interpolating_node_pt (const unsigned &n, const int &value_id)
The velocities are isoparametric and so the "nodes" interpolating the velocities are the geometric nodes. The pressure "nodes" are a subset of the nodes, so when value_id==DIM, the n-th pressure node is returned.
double local_one_d_fraction_of_interpolating_node (const unsigned &n_1d, const unsigned &i, const int &value_id)
The pressure nodes are the corner nodes, so when n_value==DIM, the fraction is the same as the 1D node number, 0 or 1.
Node * get_interpolating_node_at_local_coordinate (const Vector< double > &s, const int &value_id)
The velocity nodes are the same as the geometric nodes. The pressure nodes must be calculated by using the same methods as the geometric nodes, but by recalling that there are only two pressure nodes per edge.
unsigned ninterpolating_node_1d (const int &value_id)
The number of 1D pressure nodes is 2, the number of 1D velocity nodes is the same as the number of 1D geometric nodes.
unsigned ninterpolating_node (const int &value_id)
The number of pressure nodes is 2^DIM. The number of velocity nodes is the same as the number of geometric nodes.
void interpolating_basis (const Vector< double > &s, Shape &psi, const int &value_id) const
The basis interpolating the pressure is given by pshape(). / The basis interpolating the velocity is shape().
void build_fp_press_adv_diff_robin_bc_element (const unsigned &face_index)
Build FaceElements that apply the Robin boundary condition to the pressure advection diffusion problem required by Fp preconditioner.
void identify_load_data (std::set< std::pair< Data *, unsigned > > &paired_load_data)
Add to the set paired_load_data pairs containing.
RefineableQTaylorHoodSpaceTimeElement ()
Constructor.
unsigned required_nvalue (const unsigned &n) const
Number of values required at local node n. In order to simplify matters, we allocate storage for pressure variables at all the nodes and then pin those that are not used.
unsigned ncont_interpolated_values () const
Number of continuously interpolated values.
void rebuild_from_sons (Mesh *&mesh_pt)
Rebuild from sons: empty.
unsigned nrecovery_order ()
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
unsigned nvertex_node () const
Number of vertex nodes in the element.
Node * vertex_node_pt (const unsigned &j) const
Pointer to the j-th vertex node in the element.
void get_interpolated_values (const Vector< double > &s, Vector< double > &values)
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
void get_interpolated_values (const unsigned &t, const Vector< double > &s, Vector< double > &values)
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
void further_setup_hanging_nodes ()
Perform additional hanging node procedures for variables that are not interpolated by all nodes. The pressures are stored at the p_nodal_index_nst-th location in each node.
Node * pressure_node_pt (const unsigned &n_p)
Pointer to n_p-th pressure node.
Node * interpolating_node_pt (const unsigned &n, const int &value_id)
The velocities are isoparametric and so the "nodes" interpolating the velocities are the geometric nodes. The pressure "nodes" are a subset of the nodes, so when value_id==DIM, the n-th pressure node is returned.
double local_one_d_fraction_of_interpolating_node (const unsigned &n_1d, const unsigned &i, const int &value_id)
The pressure nodes are the corner nodes, so when n_value==DIM, the fraction is the same as the 1D node number, 0 or 1.
Node * get_interpolating_node_at_local_coordinate (const Vector< double > &s, const int &value_id)
The velocity nodes are the same as the geometric nodes. The pressure nodes must be calculated by using the same methods as the geometric nodes, but by recalling that there are only two pressure nodes per edge.
unsigned ninterpolating_node_1d (const int &value_id)
The number of 1D pressure nodes is 2, the number of 1D velocity nodes is the same as the number of 1D geometric nodes.
unsigned ninterpolating_node (const int &value_id)
The number of pressure nodes is 2^DIM. The number of velocity nodes is the same as the number of geometric nodes.
void interpolating_basis (const Vector< double > &s, Shape &psi, const int &value_id) const
The basis interpolating the pressure is given by pshape(). / The basis interpolating the velocity is shape().
void build_fp_press_adv_diff_robin_bc_element (const unsigned &face_index)
Build FaceElements that apply the Robin boundary condition to the pressure advection diffusion problem required by Fp preconditioner.
void identify_load_data (std::set< std::pair< Data *, unsigned > > &paired_load_data)
Add to the set paired_load_data pairs containing.
Public Member Functions inherited from oomph::QTaylorHoodSpaceTimeElement< DIM >
QTaylorHoodSpaceTimeElement ()
Constructor, no internal data points.
void pshape_nst (const Vector< double > &s, Shape &psi) const
Pressure shape functions at local coordinate s.
void ptest_nst (const Vector< double > &s, Shape &psi) const
Pressure test functions at local coordinate s.
void pshape_nst (const Vector< double > &s, Shape &psi, Shape &test) const
Pressure shape and test functions at local coordinte s.
virtual int p_nodal_index_nst () const
Set the value at which the pressure is stored in the nodes.
int p_local_eqn (const unsigned &n) const
Return the local equation numbers for the pressure values.
double p_nst (const unsigned &n_p) const
Access function for the pressure values at local pressure node n_p (const version)
double p_nst (const unsigned &t, const unsigned &n_p) const
Access function for the pressure values at local pressure node n_p (const version)
unsigned npres_nst () const
Return number of pressure values.
void fix_pressure (const unsigned &p_dof, const double &p_value)
Pin p_dof-th pressure dof and set it to value specified by p_value.
void identify_pressure_data (std::set< std::pair< Data *, unsigned > > &paired_pressure_data)
Add to the set paired_pressure_data pairs containing.
void output (std::ostream &outfile)
Redirect output to NavierStokesEquations output.
void output (std::ostream &outfile, const unsigned &nplot)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt, const unsigned &nplot)
Redirect output to NavierStokesEquations output.
unsigned ndof_types () const
Returns the number of "DOF types" that degrees of freedom in this element are sub-divided into: Velocity and pressure.
void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned > > &dof_lookup_list) const
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the "DOF type" that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.) Velocity=0; Pressure=1.
QTaylorHoodSpaceTimeElement ()
Constructor, no internal data points.
~QTaylorHoodSpaceTimeElement ()
void pshape_nst (const Vector< double > &s, Shape &psi) const
Pressure shape functions at local coordinate s.
void ptest_nst (const Vector< double > &s, Shape &psi) const
Pressure test functions at local coordinate s.
void pshape_nst (const Vector< double > &s, Shape &psi, Shape &test) const
Pressure shape and test functions at local coordinte s.
virtual int p_nodal_index_nst () const
Set the value at which the pressure is stored in the nodes.
int p_local_eqn (const unsigned &n) const
Return the local equation numbers for the pressure values.
double p_nst (const unsigned &n_p) const
Access function for the pressure values at local pressure node n_p (const version)
double p_nst (const unsigned &t, const unsigned &n_p) const
Access function for the pressure values at local pressure node n_p (const version)
unsigned npres_nst () const
Return number of pressure values.
void fix_pressure (const unsigned &p_dof, const double &p_value)
Pin p_dof-th pressure dof and set it to value specified by p_value.
void identify_pressure_data (std::set< std::pair< Data *, unsigned > > &paired_pressure_data)
Add to the set paired_pressure_data pairs containing.
void output (std::ostream &outfile)
Redirect output to NavierStokesEquations output.
void output (std::ostream &outfile, const unsigned &nplot)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt, const unsigned &nplot)
Redirect output to NavierStokesEquations output.
QTaylorHoodSpaceTimeElement ()
Constructor, no internal data points.
void pshape_nst (const Vector< double > &s, Shape &psi) const
Pressure shape functions at local coordinate s.
void pshape_nst (const Vector< double > &s, Shape &psi, Shape &test) const
Pressure shape and test functions at local coordinte s.
virtual int p_nodal_index_nst () const
Set the value at which the pressure is stored in the nodes.
int p_local_eqn (const unsigned &n) const
Return the local equation numbers for the pressure values.
double p_nst (const unsigned &n_p) const
Access function for the pressure values at local pressure node n_p (const version)
double p_nst (const unsigned &t, const unsigned &n_p) const
Access function for the pressure values at local pressure node n_p (const version)
unsigned npres_nst () const
Return number of pressure values.
void fix_pressure (const unsigned &p_dof, const double &p_value)
Pin p_dof-th pressure dof and set it to value specified by p_value.
void identify_pressure_data (std::set< std::pair< Data *, unsigned > > &paired_pressure_data)
Add to the set paired_pressure_data pairs containing.
void output (std::ostream &outfile)
Redirect output to NavierStokesEquations output.
void output (std::ostream &outfile, const unsigned &nplot)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt, const unsigned &nplot)
Redirect output to NavierStokesEquations output.
void pshape_nst (const Vector< double > &s, Shape &psi) const
2D (in space): Pressure shape functions
void ptest_nst (const Vector< double > &s, Shape &test) const
2D (in space): Pressure shape functions
void pshape_nst (const Vector< double > &s, Shape &psi) const
2D (in space): Pressure shape functions
void ptest_nst (const Vector< double > &s, Shape &test) const
2D (in space): Pressure shape functions
void pshape_nst (const Vector< double > &s, Shape &psi) const
2D (in space): Pressure shape functions
Public Member Functions inherited from oomph::SpaceTimeNavierStokesEquations< DIM >
SpaceTimeNavierStokesEquations ()
Constructor: NULL the body force and source function and make sure the ALE terms are included by default.
void store_strouhal_as_external_data (Data *strouhal_data_pt)
Function that tells us whether the period is stored as external data.
const double & re () const
Reynolds number.
double *& re_pt ()
Pointer to Reynolds number.
bool is_strouhal_stored_as_external_data () const
Are we storing the Strouhal number as external data?
const double & st () const
Strouhal parameter (const. version)
double * st_pt () const
Pointer to Strouhal parameter (const. version)
double *& st_pt ()
Pointer to Strouhal number (can only assign to private member data)
double re_st () const
Product of Reynolds and Strouhal number (=Womersley number)
const double & viscosity_ratio () const
Viscosity ratio for element: Element's viscosity relative to the viscosity used in the definition of the Reynolds number.
double *& viscosity_ratio_pt ()
Pointer to Viscosity Ratio.
const double & density_ratio () const
Density ratio for element: Element's density relative to the viscosity used in the definition of the Reynolds number.
double *& density_ratio_pt ()
Pointer to Density ratio.
const double & re_invfr () const
Global inverse Froude number.
double *& re_invfr_pt ()
Pointer to global inverse Froude number.
const Vector< double > & g () const
Vector of gravitational components.
Vector< double > *& g_pt ()
Pointer to Vector of gravitational components.
NavierStokesBodyForceFctPt & body_force_fct_pt ()
Access function for the body-force pointer.
NavierStokesBodyForceFctPt body_force_fct_pt () const
Access function for the body-force pointer. Const version.
NavierStokesSourceFctPt & source_fct_pt ()
Access function for the source-function pointer.
NavierStokesSourceFctPt source_fct_pt () const
Access function for the source-function pointer. Const version.
NavierStokesPressureAdvDiffSourceFctPt & source_fct_for_pressure_adv_diff ()
Access function for the source-function pointer for pressure advection diffusion (used for validation only).
NavierStokesPressureAdvDiffSourceFctPt source_fct_for_pressure_adv_diff () const
Access function for the source-function pointer for pressure advection diffusion (used for validation only). Const version.
int & pinned_fp_pressure_eqn ()
Global eqn number of pressure dof that's pinned in pressure adv diff problem.
double u_nst (const unsigned &n, const unsigned &i) const
Velocity i at local node n. Uses suitably interpolated value for hanging nodes. The use of u_index_nst() permits the use of this element as the basis for multi-physics elements. The default is to assume that the i-th velocity component is stored at the i-th location of the node.
double u_nst (const unsigned &t, const unsigned &n, const unsigned &i) const
Velocity i at local node n at timestep t (t=0: present; t>0: previous). Uses suitably interpolated value for hanging nodes.
virtual unsigned u_index_nst (const unsigned &i) const
Return the index at which the i-th unknown velocity component is stored. The default value, i, is appropriate for single-physics problems. In derived multi-physics elements, this function should be overloaded to reflect the chosen storage scheme. Note that these equations require that the unknowns are always stored at the same indices at each node.
unsigned n_u_nst () const
Return the number of velocity components (used in FluidInterfaceElements)
double get_du_dt (const unsigned &n, const unsigned &i) const
i-th component of du/dt at local node n. Uses suitably interpolated value for hanging nodes. NOTE: This is essentially a wrapper for du_dt_nst() so it can be called externally.
double du_dt_nst (const unsigned &n, const unsigned &i) const
i-th component of du/dt at local node n. Uses suitably interpolated value for hanging nodes.
double interpolated_du_dt_nst (const Vector< double > &s, const unsigned &i) const
Return FE representation of function value du_i/dt(s) at local coordinate s.
void disable_ALE ()
Disable ALE, i.e. assert the mesh is not moving -- you do this at your own risk!
void enable_ALE ()
(Re-)enable ALE, i.e. take possible mesh motion into account when evaluating the time-derivative. Note: By default, ALE is enabled, at the expense of possibly creating unnecessary work in problems where the mesh is, in fact, stationary.
double pressure_integral () const
Integral of pressure over element.
double dissipation () const
Return integral of dissipation over element.
double dissipation (const Vector< double > &s) const
Return dissipation at local coordinate s.
void get_vorticity (const Vector< double > &s, Vector< double > &vorticity) const
Compute the vorticity vector at local coordinate s.
void get_vorticity (const Vector< double > &s, double &vorticity) const
Compute the vorticity vector at local coordinate s.
double kin_energy () const
Get integral of kinetic energy over element.
double d_kin_energy_dt () const
Get integral of time derivative of kinetic energy over element.
void strain_rate (const Vector< double > &s, DenseMatrix< double > &strain_rate) const
Strain-rate tensor: 1/2 (du_i/dx_j+du_j/dx_i)
void get_traction (const Vector< double > &s, const Vector< double > &N, Vector< double > &traction)
Compute traction (on the viscous scale) exerted onto the fluid at local coordinate s. N has to be outer unit normal to the fluid.
void get_traction (const Vector< double > &s, const Vector< double > &N, Vector< double > &traction_p, Vector< double > &traction_visc_n, Vector< double > &traction_visc_t)
Compute traction (on the viscous scale) exerted onto the fluid at local coordinate s, decomposed into pressure and normal and tangential viscous components. N has to be outer unit normal to the fluid.
void get_load (const Vector< double > &s, const Vector< double > &N, Vector< double > &load)
This implements a pure virtual function defined in the FSIFluidElement class. The function computes the traction (on the viscous scale), at the element's local coordinate s, that the fluid element exerts onto an adjacent solid element. The number of arguments is imposed by the interface defined in the FSIFluidElement -- only the unit normal N (pointing into the fluid!) is actually used in the computation.
void get_pressure_and_velocity_mass_matrix_diagonal (Vector< double > &press_mass_diag, Vector< double > &veloc_mass_diag, const unsigned &which_one=0)
Compute the diagonal of the velocity/pressure mass matrices. If which one=0, both are computed, otherwise only the pressure (which_one=1) or the velocity mass matrix (which_one=2 -- the LSC version of the preconditioner only needs that one)
unsigned nscalar_paraview () const
Number of scalars/fields output by this element. Reimplements broken virtual function in base class.
void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
Write values of the i-th scalar field at the plot points. Needs to be implemented for each new specific element type.
void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
Write values of the i-th scalar field at the plot points. Needs to be implemented for each new specific element type.
std::string scalar_name_paraview (const unsigned &i) const
Name of the i-th scalar field. Default implementation returns V1 for the first one, V2 for the second etc. Can (should!) be overloaded with more meaningful names in specific elements.
void output (std::ostream &outfile)
Output function: x,y,t,u,v,p in tecplot format. The default number of plot points is five.
void output (std::ostream &outfile, const unsigned &n_plot)
Output function: x,y,[z],u,v,[w],p in tecplot format. Here, we use n_plot plot points in each coordinate direction.
void output (FILE *file_pt)
C-style output function: x,y,[z],u,v,[w],p in tecplot format. The default number of plot points is five.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function: x,y,[z],u,v,[w],p in tecplot format. Use n_plot points in each coordinate direction.
void full_output (std::ostream &outfile)
Full output function: x,y,[z],u,v,[w],p,du/dt,dv/dt,[dw/dt],dissipation in tecplot format. The default number of plot points is five.
void full_output (std::ostream &outfile, const unsigned &n_plot)
Full output function: x,y,t,u,v,p,du/dt,dv/dt,dissipation in tecplot format. Use n_plot plot points in each coordinate direction.
void output_veloc (std::ostream &outfile, const unsigned &nplot, const unsigned &t)
Output function: x,y,t,u,v in tecplot format. Use n_plot points in each coordinate direction at timestep t (t=0: present; t>0: previous timestep)
void output_vorticity (std::ostream &outfile, const unsigned &nplot)
Output function: x,y,t,omega in tecplot format. nplot points in each coordinate direction.
void output_fct (std::ostream &outfile, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output exact solution specified via function pointer at a given number of plot points. Function prints as many components as are returned in solution Vector.
void output_fct (std::ostream &outfile, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output exact solution specified via function pointer at a given time and at a given number of plot points. Function prints as many components as are returned in solution Vector.
void compute_norm (Vector< double > &norm)
Compute the vector norm of the FEM solution.
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Validate against exact solution at given time Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element.
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
Validate against exact solution at given time Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element.
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Validate against exact solution. Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element.
void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Validate against exact solution. Solution is provided via function pointer. Compute L2 error and L2 norm of velocity solution over element.
void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Validate against exact solution. Solution is provided via function pointer. Compute L2 error and L2 norm of velocity solution over element.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Compute the element's residual Vector.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Compute the element's residual Vector and the jacobian matrix Virtual function can be overloaded by hanging-node version.
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix.
void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
Compute the element's residual Vector (differentiated w.r.t. a parameter)
void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
Compute the element's residual Vector and the jacobian matrix Virtual function can be overloaded by hanging-node version.
void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix.
void fill_in_pressure_advection_diffusion_residuals (Vector< double > &residuals)
Compute the residuals for the associated pressure advection diffusion problem. Used by the Fp preconditioner.
void fill_in_pressure_advection_diffusion_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Compute the residuals and Jacobian for the associated pressure advection diffusion problem. Used by the Fp preconditioner.
void pin_all_non_pressure_dofs (std::map< Data *, std::vector< int > > &eqn_number_backup)
Pin all non-pressure dofs and backup eqn numbers.
void output_pressure_advection_diffusion_robin_elements (std::ostream &outfile)
Output the FaceElements that apply the Robin boundary condition to the pressure advection diffusion problem required by Fp preconditioner.
void delete_pressure_advection_diffusion_robin_elements ()
Delete the FaceElements that apply the Robin boundary condition to the pressure advection diffusion problem required by Fp preconditioner.
void interpolated_u_nst (const Vector< double > &s, Vector< double > &velocity) const
Compute vector of FE interpolated velocity u at local coordinate s.
double interpolated_u_nst (const Vector< double > &s, const unsigned &i) const
Return FE interpolated velocity u[i] at local coordinate s.
double interpolated_u_nst (const unsigned &t, const Vector< double > &s, const unsigned &i) const
Return FE interpolated velocity u[i] at local coordinate s time level, t. Purposely broken for space-time elements.
virtual double interpolated_p_nst (const Vector< double > &s) const
Return FE interpolated pressure at local coordinate s.
double interpolated_p_nst (const unsigned &t, const Vector< double > &s) const
Return FE interpolated pressure at local coordinate s at time level t.
void point_output_data (const Vector< double > &s, Vector< double > &data)
Output solution in data vector at local cordinates s: x,y,z,u,v,p.
SpaceTimeNavierStokesEquations ()
Constructor: NULL the body force and source function and make sure the ALE terms are included by default.
void store_strouhal_as_external_data (Data *strouhal_data_pt)
Function that tells us whether the period is stored as external data.
const double & re () const
Reynolds number.
double *& re_pt ()
Pointer to Reynolds number.
bool is_strouhal_stored_as_external_data () const
Are we storing the Strouhal number as external data?
const double & st () const
Strouhal parameter (const. version)
double * st_pt () const
Pointer to Strouhal parameter (const. version)
double *& st_pt ()
Pointer to Strouhal number (can only assign to private member data)
double re_st () const
Product of Reynolds and Strouhal number (=Womersley number)
const double & viscosity_ratio () const
Viscosity ratio for element: Element's viscosity relative to the viscosity used in the definition of the Reynolds number.
double *& viscosity_ratio_pt ()
Pointer to Viscosity Ratio.
const double & density_ratio () const
Density ratio for element: Element's density relative to the viscosity used in the definition of the Reynolds number.
double *& density_ratio_pt ()
Pointer to Density ratio.
const double & re_invfr () const
Global inverse Froude number.
double *& re_invfr_pt ()
Pointer to global inverse Froude number.
const Vector< double > & g () const
Vector of gravitational components.
Vector< double > *& g_pt ()
Pointer to Vector of gravitational components.
NavierStokesBodyForceFctPt & body_force_fct_pt ()
Access function for the body-force pointer.
NavierStokesBodyForceFctPt body_force_fct_pt () const
Access function for the body-force pointer. Const version.
NavierStokesSourceFctPt & source_fct_pt ()
Access function for the source-function pointer.
NavierStokesSourceFctPt source_fct_pt () const
Access function for the source-function pointer. Const version.
NavierStokesPressureAdvDiffSourceFctPt & source_fct_for_pressure_adv_diff ()
Access function for the source-function pointer for pressure advection diffusion (used for validation only).
NavierStokesPressureAdvDiffSourceFctPt source_fct_for_pressure_adv_diff () const
Access function for the source-function pointer for pressure advection diffusion (used for validation only). Const version.
int & pinned_fp_pressure_eqn ()
Global eqn number of pressure dof that's pinned in pressure adv diff problem.
double u_nst (const unsigned &n, const unsigned &i) const
Velocity i at local node n. Uses suitably interpolated value for hanging nodes. The use of u_index_nst() permits the use of this element as the basis for multi-physics elements. The default is to assume that the i-th velocity component is stored at the i-th location of the node.
double u_nst (const unsigned &t, const unsigned &n, const unsigned &i) const
Velocity i at local node n at timestep t (t=0: present; t>0: previous). Uses suitably interpolated value for hanging nodes.
virtual unsigned u_index_nst (const unsigned &i) const
Return the index at which the i-th unknown velocity component is stored. The default value, i, is appropriate for single-physics problems. In derived multi-physics elements, this function should be overloaded to reflect the chosen storage scheme. Note that these equations require that the unknowns are always stored at the same indices at each node.
unsigned n_u_nst () const
Return the number of velocity components (used in FluidInterfaceElements)
double get_du_dt (const unsigned &n, const unsigned &i) const
i-th component of du/dt at local node n. Uses suitably interpolated value for hanging nodes. NOTE: This is essentially a wrapper for du_dt_nst() so it can be called externally.
double du_dt_nst (const unsigned &n, const unsigned &i) const
i-th component of du/dt at local node n. Uses suitably interpolated value for hanging nodes.
double interpolated_du_dt_nst (const Vector< double > &s, const unsigned &i) const
Return FE representation of function value du_i/dt(s) at local coordinate s.
void disable_ALE ()
Disable ALE, i.e. assert the mesh is not moving -- you do this at your own risk!
void enable_ALE ()
(Re-)enable ALE, i.e. take possible mesh motion into account when evaluating the time-derivative. Note: By default, ALE is enabled, at the expense of possibly creating unnecessary work in problems where the mesh is, in fact, stationary.
double pressure_integral () const
Integral of pressure over element.
double dissipation () const
Return integral of dissipation over element.
double dissipation (const Vector< double > &s) const
Return dissipation at local coordinate s.
void get_vorticity (const Vector< double > &s, Vector< double > &vorticity) const
Compute the vorticity vector at local coordinate s.
void get_vorticity (const Vector< double > &s, double &vorticity) const
Compute the vorticity vector at local coordinate s.
double kin_energy () const
Get integral of kinetic energy over element.
double d_kin_energy_dt () const
Get integral of time derivative of kinetic energy over element.
void strain_rate (const Vector< double > &s, DenseMatrix< double > &strain_rate) const
Strain-rate tensor: 1/2 (du_i/dx_j+du_j/dx_i)
void get_traction (const Vector< double > &s, const Vector< double > &N, Vector< double > &traction)
Compute traction (on the viscous scale) exerted onto the fluid at local coordinate s. N has to be outer unit normal to the fluid.
void get_traction (const Vector< double > &s, const Vector< double > &N, Vector< double > &traction_p, Vector< double > &traction_visc_n, Vector< double > &traction_visc_t)
Compute traction (on the viscous scale) exerted onto the fluid at local coordinate s, decomposed into pressure and normal and tangential viscous components. N has to be outer unit normal to the fluid.
void get_load (const Vector< double > &s, const Vector< double > &N, Vector< double > &load)
This implements a pure virtual function defined in the FSIFluidElement class. The function computes the traction (on the viscous scale), at the element's local coordinate s, that the fluid element exerts onto an adjacent solid element. The number of arguments is imposed by the interface defined in the FSIFluidElement -- only the unit normal N (pointing into the fluid!) is actually used in the computation.
void get_pressure_and_velocity_mass_matrix_diagonal (Vector< double > &press_mass_diag, Vector< double > &veloc_mass_diag, const unsigned &which_one=0)
Compute the diagonal of the velocity/pressure mass matrices. If which one=0, both are computed, otherwise only the pressure (which_one=1) or the velocity mass matrix (which_one=2 -- the LSC version of the preconditioner only needs that one)
unsigned nscalar_paraview () const
Number of scalars/fields output by this element. Reimplements broken virtual function in base class.
void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
Write values of the i-th scalar field at the plot points. Needs to be implemented for each new specific element type.
void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
Write values of the i-th scalar field at the plot points. Needs to be implemented for each new specific element type.
std::string scalar_name_paraview (const unsigned &i) const
Name of the i-th scalar field. Default implementation returns V1 for the first one, V2 for the second etc. Can (should!) be overloaded with more meaningful names in specific elements.
void output (std::ostream &outfile)
Output function: x,y,t,u,v,p in tecplot format. The default number of plot points is five.
void output (std::ostream &outfile, const unsigned &n_plot)
Output function: x,y,[z],u,v,[w],p in tecplot format. Here, we use n_plot plot points in each coordinate direction.
void output (FILE *file_pt)
C-style output function: x,y,[z],u,v,[w],p in tecplot format. The default number of plot points is five.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function: x,y,[z],u,v,[w],p in tecplot format. Use n_plot points in each coordinate direction.
void full_output (std::ostream &outfile)
Full output function: x,y,[z],u,v,[w],p,du/dt,dv/dt,[dw/dt],dissipation in tecplot format. The default number of plot points is five.
void full_output (std::ostream &outfile, const unsigned &n_plot)
Full output function: x,y,t,u,v,p,du/dt,dv/dt,dissipation in tecplot format. Use n_plot plot points in each coordinate direction.
void output_veloc (std::ostream &outfile, const unsigned &nplot, const unsigned &t)
Output function: x,y,t,u,v in tecplot format. Use n_plot points in each coordinate direction at timestep t (t=0: present; t>0: previous timestep)
void output_vorticity (std::ostream &outfile, const unsigned &nplot)
Output function: x,y,t,omega in tecplot format. nplot points in each coordinate direction.
void output_fct (std::ostream &outfile, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output exact solution specified via function pointer at a given number of plot points. Function prints as many components as are returned in solution Vector.
void output_fct (std::ostream &outfile, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output exact solution specified via function pointer at a given time and at a given number of plot points. Function prints as many components as are returned in solution Vector.
void compute_norm (Vector< double > &norm)
Compute the vector norm of the FEM solution.
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Validate against exact solution at given time Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element.
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
Validate against exact solution at given time Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element.
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Validate against exact solution. Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element.
void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Validate against exact solution. Solution is provided via function pointer. Compute L2 error and L2 norm of velocity solution over element.
void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Validate against exact solution. Solution is provided via function pointer. Compute L2 error and L2 norm of velocity solution over element.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Compute the element's residual Vector.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Compute the element's residual Vector and the jacobian matrix Virtual function can be overloaded by hanging-node version.
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix.
void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
Compute the element's residual Vector (differentiated w.r.t. a parameter)
void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
Compute the element's residual Vector and the jacobian matrix Virtual function can be overloaded by hanging-node version.
void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix.
void fill_in_pressure_advection_diffusion_residuals (Vector< double > &residuals)
Compute the residuals for the associated pressure advection diffusion problem. Used by the Fp preconditioner.
void fill_in_pressure_advection_diffusion_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Compute the residuals and Jacobian for the associated pressure advection diffusion problem. Used by the Fp preconditioner.
void pin_all_non_pressure_dofs (std::map< Data *, std::vector< int > > &eqn_number_backup)
Pin all non-pressure dofs and backup eqn numbers.
void output_pressure_advection_diffusion_robin_elements (std::ostream &outfile)
Output the FaceElements that apply the Robin boundary condition to the pressure advection diffusion problem required by Fp preconditioner.
void delete_pressure_advection_diffusion_robin_elements ()
Delete the FaceElements that apply the Robin boundary condition to the pressure advection diffusion problem required by Fp preconditioner.
void interpolated_u_nst (const Vector< double > &s, Vector< double > &velocity) const
Compute vector of FE interpolated velocity u at local coordinate s.
double interpolated_u_nst (const Vector< double > &s, const unsigned &i) const
Return FE interpolated velocity u[i] at local coordinate s.
double interpolated_u_nst (const unsigned &t, const Vector< double > &s, const unsigned &i) const
Return FE interpolated velocity u[i] at local coordinate s time level, t. Purposely broken for space-time elements.
virtual double interpolated_p_nst (const Vector< double > &s) const
Return FE interpolated pressure at local coordinate s.
double interpolated_p_nst (const unsigned &t, const Vector< double > &s) const
Return FE interpolated pressure at local coordinate s at time level t.
void point_output_data (const Vector< double > &s, Vector< double > &data)
Output solution in data vector at local cordinates s: x,y,z,u,v,p.
SpaceTimeNavierStokesEquations ()
Constructor: NULL the body force and source function and make sure the ALE terms are included by default.
void store_strouhal_as_external_data (Data *strouhal_data_pt)
Function that tells us whether the period is stored as external data.
bool is_reynolds_strouhal_stored_as_external_data () const
Are we storing the Strouhal number as external data?
const double & re () const
Reynolds number.
double *& re_pt ()
Pointer to Reynolds number.
const double & re_st () const
ReSt parameter (const. version)
double * re_st_pt () const
Pointer to Strouhal parameter (const. version)
double *& re_st_pt ()
Pointer to ReSt number (can only assign to private member data)
const double & viscosity_ratio () const
Viscosity ratio for element: Element's viscosity relative to the viscosity used in the definition of the Reynolds number.
double *& viscosity_ratio_pt ()
Pointer to Viscosity Ratio.
const double & density_ratio () const
Density ratio for element: Element's density relative to the viscosity used in the definition of the Reynolds number.
double *& density_ratio_pt ()
Pointer to Density ratio.
const double & re_invfr () const
Global inverse Froude number.
double *& re_invfr_pt ()
Pointer to global inverse Froude number.
const Vector< double > & g () const
Vector of gravitational components.
Vector< double > *& g_pt ()
Pointer to Vector of gravitational components.
NavierStokesBodyForceFctPt & body_force_fct_pt ()
Access function for the body-force pointer.
NavierStokesBodyForceFctPt body_force_fct_pt () const
Access function for the body-force pointer. Const version.
NavierStokesSourceFctPt & source_fct_pt ()
Access function for the source-function pointer.
NavierStokesSourceFctPt source_fct_pt () const
Access function for the source-function pointer. Const version.
NavierStokesPressureAdvDiffSourceFctPt & source_fct_for_pressure_adv_diff ()
Access function for the source-function pointer for pressure advection diffusion (used for validation only).
NavierStokesPressureAdvDiffSourceFctPt source_fct_for_pressure_adv_diff () const
Access function for the source-function pointer for pressure advection diffusion (used for validation only). Const version.
int & pinned_fp_pressure_eqn ()
Global eqn number of pressure dof that's pinned in pressure adv diff problem.
double u_nst (const unsigned &n, const unsigned &i) const
Velocity i at local node n. Uses suitably interpolated value for hanging nodes. The use of u_index_nst() permits the use of this element as the basis for multi-physics elements. The default is to assume that the i-th velocity component is stored at the i-th location of the node.
double u_nst (const unsigned &t, const unsigned &n, const unsigned &i) const
Velocity i at local node n at timestep t (t=0: present; t>0: previous). Uses suitably interpolated value for hanging nodes.
virtual unsigned u_index_nst (const unsigned &i) const
Return the index at which the i-th unknown velocity component is stored. The default value, i, is appropriate for single-physics problems. In derived multi-physics elements, this function should be overloaded to reflect the chosen storage scheme. Note that these equations require that the unknowns are always stored at the same indices at each node.
unsigned n_u_nst () const
Return the number of velocity components (used in FluidInterfaceElements)
double get_du_dt (const unsigned &n, const unsigned &i) const
i-th component of du/dt at local node n. Uses suitably interpolated value for hanging nodes. NOTE: This is essentially a wrapper for du_dt_nst() so it can be called externally.
double du_dt_nst (const unsigned &n, const unsigned &i) const
i-th component of du/dt at local node n. Uses suitably interpolated value for hanging nodes.
double interpolated_du_dt_nst (const Vector< double > &s, const unsigned &i) const
Return FE representation of function value du_i/dt(s) at local coordinate s.
void disable_ALE ()
Disable ALE, i.e. assert the mesh is not moving -- you do this at your own risk!
void enable_ALE ()
(Re-)enable ALE, i.e. take possible mesh motion into account when evaluating the time-derivative. Note: By default, ALE is enabled, at the expense of possibly creating unnecessary work in problems where the mesh is, in fact, stationary.
double pressure_integral () const
Integral of pressure over element.
double dissipation () const
Return integral of dissipation over element.
double dissipation (const Vector< double > &s) const
Return dissipation at local coordinate s.
void get_vorticity (const Vector< double > &s, Vector< double > &vorticity) const
Compute the vorticity vector at local coordinate s.
void get_vorticity (const Vector< double > &s, double &vorticity) const
Compute the vorticity vector at local coordinate s.
double kin_energy () const
Get integral of kinetic energy over element.
double d_kin_energy_dt () const
Get integral of time derivative of kinetic energy over element.
void strain_rate (const Vector< double > &s, DenseMatrix< double > &strain_rate) const
Strain-rate tensor: 1/2 (du_i/dx_j+du_j/dx_i)
void get_traction (const Vector< double > &s, const Vector< double > &N, Vector< double > &traction)
Compute traction (on the viscous scale) exerted onto the fluid at local coordinate s. N has to be outer unit normal to the fluid.
void get_traction (const Vector< double > &s, const Vector< double > &N, Vector< double > &traction_p, Vector< double > &traction_visc_n, Vector< double > &traction_visc_t)
Compute traction (on the viscous scale) exerted onto the fluid at local coordinate s, decomposed into pressure and normal and tangential viscous components. N has to be outer unit normal to the fluid.
void get_load (const Vector< double > &s, const Vector< double > &N, Vector< double > &load)
This implements a pure virtual function defined in the FSIFluidElement class. The function computes the traction (on the viscous scale), at the element's local coordinate s, that the fluid element exerts onto an adjacent solid element. The number of arguments is imposed by the interface defined in the FSIFluidElement -- only the unit normal N (pointing into the fluid!) is actually used in the computation.
void get_pressure_and_velocity_mass_matrix_diagonal (Vector< double > &press_mass_diag, Vector< double > &veloc_mass_diag, const unsigned &which_one=0)
Compute the diagonal of the velocity/pressure mass matrices. If which one=0, both are computed, otherwise only the pressure (which_one=1) or the velocity mass matrix (which_one=2 -- the LSC version of the preconditioner only needs that one)
unsigned nscalar_paraview () const
Number of scalars/fields output by this element. Reimplements broken virtual function in base class.
void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
Write values of the i-th scalar field at the plot points. Needs to be implemented for each new specific element type.
void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
Write values of the i-th scalar field at the plot points. Needs to be implemented for each new specific element type.
std::string scalar_name_paraview (const unsigned &i) const
Name of the i-th scalar field. Default implementation returns V1 for the first one, V2 for the second etc. Can (should!) be overloaded with more meaningful names in specific elements.
void output (std::ostream &outfile)
Output function: x,y,t,u,v,p in tecplot format. The default number of plot points is five.
void output (std::ostream &outfile, const unsigned &n_plot)
Output function: x,y,[z],u,v,[w],p in tecplot format. Here, we use n_plot plot points in each coordinate direction.
void output (FILE *file_pt)
C-style output function: x,y,[z],u,v,[w],p in tecplot format. The default number of plot points is five.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function: x,y,[z],u,v,[w],p in tecplot format. Use n_plot points in each coordinate direction.
void full_output (std::ostream &outfile)
Full output function: x,y,[z],u,v,[w],p,du/dt,dv/dt,[dw/dt],dissipation in tecplot format. The default number of plot points is five.
void full_output (std::ostream &outfile, const unsigned &n_plot)
Full output function: x,y,t,u,v,p,du/dt,dv/dt,dissipation in tecplot format. Use n_plot plot points in each coordinate direction.
void output_veloc (std::ostream &outfile, const unsigned &nplot, const unsigned &t)
Output function: x,y,t,u,v in tecplot format. Use n_plot points in each coordinate direction at timestep t (t=0: present; t>0: previous timestep)
void output_vorticity (std::ostream &outfile, const unsigned &nplot)
Output function: x,y,t,omega in tecplot format. nplot points in each coordinate direction.
void output_fct (std::ostream &outfile, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output exact solution specified via function pointer at a given number of plot points. Function prints as many components as are returned in solution Vector.
void output_fct (std::ostream &outfile, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output exact solution specified via function pointer at a given time and at a given number of plot points. Function prints as many components as are returned in solution Vector.
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Validate against exact solution at given time Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element.
void compute_norm (Vector< double > &norm)
Compute the vector norm of the FEM solution.
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
Validate against exact solution at given time Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element.
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Validate against exact solution. Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element.
void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Validate against exact solution. Solution is provided via function pointer. Compute L2 error and L2 norm of velocity solution over element.
void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Validate against exact solution. Solution is provided via function pointer. Compute L2 error and L2 norm of velocity solution over element.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Compute the element's residual Vector.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Compute the element's residual Vector and the jacobian matrix Virtual function can be overloaded by hanging-node version.
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix.
void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
Compute the element's residual Vector (differentiated w.r.t. a parameter)
void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
Compute the element's residual Vector and the jacobian matrix Virtual function can be overloaded by hanging-node version.
void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix.
void fill_in_pressure_advection_diffusion_residuals (Vector< double > &residuals)
Compute the residuals for the associated pressure advection diffusion problem. Used by the Fp preconditioner.
void fill_in_pressure_advection_diffusion_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Compute the residuals and Jacobian for the associated pressure advection diffusion problem. Used by the Fp preconditioner.
void pin_all_non_pressure_dofs (std::map< Data *, std::vector< int > > &eqn_number_backup)
Pin all non-pressure dofs and backup eqn numbers.
void output_pressure_advection_diffusion_robin_elements (std::ostream &outfile)
Output the FaceElements that apply the Robin boundary condition to the pressure advection diffusion problem required by Fp preconditioner.
void delete_pressure_advection_diffusion_robin_elements ()
Delete the FaceElements that apply the Robin boundary condition to the pressure advection diffusion problem required by Fp preconditioner.
void interpolated_u_nst (const Vector< double > &s, Vector< double > &velocity) const
Compute vector of FE interpolated velocity u at local coordinate s.
double interpolated_u_nst (const Vector< double > &s, const unsigned &i) const
Return FE interpolated velocity u[i] at local coordinate s.
double interpolated_u_nst (const unsigned &t, const Vector< double > &s, const unsigned &i) const
Return FE interpolated velocity u[i] at local coordinate s time level, t. Purposely broken for space-time elements.
virtual double interpolated_p_nst (const Vector< double > &s) const
Return FE interpolated pressure at local coordinate s.
double interpolated_p_nst (const unsigned &t, const Vector< double > &s) const
Return FE interpolated pressure at local coordinate s at time level t.
void point_output_data (const Vector< double > &s, Vector< double > &data)
Output solution in data vector at local cordinates s: x,y,z,u,v,p.
void get_vorticity (const Vector< double > &s, Vector< double > &vorticity) const
Compute 2D vorticity vector at local coordinate s (return in one and only component of vorticity vector.
void get_vorticity (const Vector< double > &s, double &vorticity) const
Compute 2D vorticity vector at local coordinate s (return in one and only component of vorticity vector as a double.
void get_vorticity (const Vector< double > &s, Vector< double > &vorticity) const
Compute 2D vorticity vector at local coordinate s (return in one and only component of vorticity vector.
void get_vorticity (const Vector< double > &s, double &vorticity) const
Compute 2D vorticity vector at local coordinate s (return in one and only component of vorticity vector as a double.
void get_vorticity (const Vector< double > &s, Vector< double > &vorticity) const
Compute 2D vorticity vector at local coordinate s (return in one and only component of vorticity vector.
void get_vorticity (const Vector< double > &s, double &vorticity) const
Compute 2D vorticity vector at local coordinate s (return in one and only component of vorticity vector as a double.
Public Member Functions inherited from oomph::FSIFluidElement
FSIFluidElement ()
Constructor.
FSIFluidElement (const FSIFluidElement &)=delete
Broken copy constructor.
void operator= (const FSIFluidElement &)=delete
Broken assignment operator.
Public Member Functions inherited from oomph::FiniteElement
void set_dimension (const unsigned &dim)
Set the dimension of the element and initially set the dimension of the nodes to be the same as the dimension of the element.
void set_nodal_dimension (const unsigned &nodal_dim)
Set the dimension of the nodes in the element. This will typically only be required when constructing FaceElements or in beam and shell type elements where a lower dimensional surface is embedded in a higher dimensional space.
void set_nnodal_position_type (const unsigned &nposition_type)
Set the number of types required to interpolate the coordinate.
void set_n_node (const unsigned &n)
Set the number of nodes in the element to n, by resizing the storage for pointers to the Node objects.
int nodal_local_eqn (const unsigned &n, const unsigned &i) const
Return the local equation number corresponding to the i-th value at the n-th local node.
double dJ_eulerian_at_knot (const unsigned &ipt, Shape &psi, DenseMatrix< double > &djacobian_dX) const
Compute the geometric shape functions (psi) at integration point ipt. Return the determinant of the jacobian of the mapping (detJ). Additionally calculate the derivatives of "detJ" w.r.t. the nodal coordinates.
FiniteElement ()
Constructor.
virtual ~FiniteElement ()
The destructor cleans up the static memory allocated for shape function storage. Internal and external data get wiped by the GeneralisedElement destructor; nodes get killed in mesh destructor.
FiniteElement (const FiniteElement &)=delete
Broken copy constructor.
virtual bool local_coord_is_valid (const Vector< double > &s)
Broken assignment operator.
virtual void move_local_coord_back_into_element (Vector< double > &s) const
Adjust local coordinates so that they're located inside the element.
void get_centre_of_gravity_and_max_radius_in_terms_of_zeta (Vector< double > &cog, double &max_radius) const
Compute centre of gravity of all nodes and radius of node that is furthest from it. Used to assess approximately if a point is likely to be contained with an element in locate_zeta-like operations.
virtual void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
Get local coordinates of node j in the element; vector sets its own size (broken virtual)
virtual void local_fraction_of_node (const unsigned &j, Vector< double > &s_fraction)
Get the local fraction of the node j in the element A dumb, but correct default implementation is provided.
virtual double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
Get the local fraction of any node in the n-th position in a one dimensional expansion along the i-th local coordinate.
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt)
Set pointer to macro element -- can be overloaded in derived elements to perform additional tasks.
MacroElement * macro_elem_pt ()
Access function to pointer to macro element.
void get_x (const Vector< double > &s, Vector< double > &x) const
Global coordinates as function of local coordinates. Either via FE representation or via macro-element (if Macro_elem_pt!=0)
void get_x (const unsigned &t, const Vector< double > &s, Vector< double > &x)
Global coordinates as function of local coordinates at previous time "level" t (t=0: present; t>0: previous). Either via FE representation of QElement or via macro-element (if Macro_elem_pt!=0).
virtual void get_x_from_macro_element (const Vector< double > &s, Vector< double > &x) const
Global coordinates as function of local coordinates using macro element representation. (Broken virtual --- this must be overloaded in specific geometric element classes)
virtual void get_x_from_macro_element (const unsigned &t, const Vector< double > &s, Vector< double > &x)
Global coordinates as function of local coordinates at previous time "level" t (t=0: present; t>0: previous). using macro element representation (Broken virtual -- overload in specific geometric element class if you want to use this functionality.)
virtual void set_integration_scheme (Integral *const &integral_pt)
Set the spatial integration scheme.
Integral *const & integral_pt () const
Return the pointer to the integration scheme (const version)
virtual void shape (const Vector< double > &s, Shape &psi) const =0
Calculate the geometric shape functions at local coordinate s. This function must be overloaded for each specific geometric element.
virtual void shape_at_knot (const unsigned &ipt, Shape &psi) const
Return the geometric shape function at the ipt-th integration point.
virtual void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
Function to compute the geometric shape functions and derivatives w.r.t. local coordinates at local coordinate s. This function must be overloaded for each specific geometric element. (Broken virtual function --- specifies the interface)
virtual void dshape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
Return the geometric shape function and its derivative w.r.t. the local coordinates at the ipt-th integration point.
virtual void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
Function to compute the geometric shape functions and also first and second derivatives w.r.t. local coordinates at local coordinate s. This function must be overloaded for each specific geometric element (if required). (Broken virtual function --- specifies the interface). Numbering: 1D: d2psids(i,0) = $ d^2 \psi_j / ds^2 $ 2D: d2psids(i,0) = $ \partial^2 \psi_j / \partial s_0^2 $ d2psids(i,1) = $ \partial^2 \psi_j / \partial s_1^2 $ d2psids(i,2) = $ \partial^2 \psi_j / \partial s_0 \partial s_1 $ 3D: d2psids(i,0) = $ \partial^2 \psi_j / \partial s_0^2 $ d2psids(i,1) = $ \partial^2 \psi_j / \partial s_1^2 $ d2psids(i,2) = $ \partial^2 \psi_j / \partial s_2^2 $ d2psids(i,3) = $ \partial^2 \psi_j / \partial s_0 \partial s_1 $ d2psids(i,4) = $ \partial^2 \psi_j / \partial s_0 \partial s_2 $ d2psids(i,5) = $ \partial^2 \psi_j / \partial s_1 \partial s_2 $.
virtual void d2shape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
Return the geometric shape function and its first and second derivatives w.r.t. the local coordinates at the ipt-th integration point. Numbering: 1D: d2psids(i,0) = $ d^2 \psi_j / ds^2 $ 2D: d2psids(i,0) = $ \partial^2 \psi_j / \partial s_0^2 $ d2psids(i,1) = $ \partial^2 \psi_j / \partial s_1^2 $ d2psids(i,2) = $ \partial^2 \psi_j / \partial s_0 \partial s_1 $ 3D: d2psids(i,0) = $ \partial^2 \psi_j / \partial s_0^2 $ d2psids(i,1) = $ \partial^2 \psi_j / \partial s_1^2 $ d2psids(i,2) = $ \partial^2 \psi_j / \partial s_2^2 $ d2psids(i,3) = $ \partial^2 \psi_j / \partial s_0 \partial s_1 $ d2psids(i,4) = $ \partial^2 \psi_j / \partial s_0 \partial s_2 $ d2psids(i,5) = $ \partial^2 \psi_j / \partial s_1 \partial s_2 $.
virtual double J_eulerian (const Vector< double > &s) const
Return the Jacobian of mapping from local to global coordinates at local position s.
virtual double J_eulerian_at_knot (const unsigned &ipt) const
Return the Jacobian of the mapping from local to global coordinates at the ipt-th integration point.
void check_J_eulerian_at_knots (bool &passed) const
Check that Jacobian of mapping between local and Eulerian coordinates at all integration points is positive.
void check_jacobian (const double &jacobian) const
Helper function used to check for singular or negative Jacobians in the transform from local to global or Lagrangian coordinates.
double dshape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
Compute the geometric shape functions and also first derivatives w.r.t. global coordinates at local coordinate s; Returns Jacobian of mapping from global to local coordinates.
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx) const
Return the geometric shape functions and also first derivatives w.r.t. global coordinates at the ipt-th integration point.
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, DenseMatrix< double > &djacobian_dX, RankFourTensor< double > &d_dpsidx_dX) const
Compute the geometric shape functions (psi) and first derivatives w.r.t. global coordinates (dpsidx) at the ipt-th integration point. Return the determinant of the jacobian of the mapping (detJ). Additionally calculate the derivatives of both "detJ" and "dpsidx" w.r.t. the nodal coordinates.
double d2shape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
Compute the geometric shape functions and also first and second derivatives w.r.t. global coordinates at local coordinate s; Returns Jacobian of mapping from global to local coordinates. Numbering: 1D: d2psidx(i,0) = $ d^2 \psi_j / d x^2 $ 2D: d2psidx(i,0) = $ \partial^2 \psi_j / \partial x_0^2 $ d2psidx(i,1) = $ \partial^2 \psi_j / \partial x_1^2 $ d2psidx(i,2) = $ \partial^2 \psi_j / \partial x_0 \partial x_1 $ 3D: d2psidx(i,0) = $ \partial^2 \psi_j / \partial x_0^2 $ d2psidx(i,1) = $ \partial^2 \psi_j / \partial x_1^2 $ d2psidx(i,2) = $ \partial^2 \psi_j / \partial x_2^2 $ d2psidx(i,3) = $ \partial^2 \psi_j / \partial x_0 \partial x_1 $ d2psidx(i,4) = $ \partial^2 \psi_j / \partial x_0 \partial x_2 $ d2psidx(i,5) = $ \partial^2 \psi_j / \partial x_1 \partial x_2 $.
virtual double d2shape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
Return the geometric shape functions and also first and second derivatives w.r.t. global coordinates at ipt-th integration point. Numbering: 1D: d2psidx(i,0) = $ d^2 \psi_j / d s^2 $ 2D: d2psidx(i,0) = $ \partial^2 \psi_j / \partial x_0^2 $ d2psidx(i,1) = $ \partial^2 \psi_j / \partial x_1^2 $ d2psidx(i,2) = $ \partial^2 \psi_j / \partial x_0 \partial x_1 $ 3D: d2psidx(i,0) = $ \partial^2 \psi_j / \partial x_0^2 $ d2psidx(i,1) = $ \partial^2 \psi_j / \partial x_1^2 $ d2psidx(i,2) = $ \partial^2 \psi_j / \partial x_2^2 $ d2psidx(i,3) = $ \partial^2 \psi_j / \partial x_0 \partial x_1 $ d2psidx(i,4) = $ \partial^2 \psi_j / \partial x_0 \partial x_2 $ d2psidx(i,5) = $ \partial^2 \psi_j / \partial x_1 \partial x_2 $.
virtual void describe_local_dofs (std::ostream &out, const std::string &current_string) const
Function to describe the local dofs of the element[s]. The ostream specifies the output stream to which the description is written; the string stores the currently assembled output that is ultimately written to the output stream by Data::describe_dofs(...); it is typically built up incrementally as we descend through the call hierarchy of this function when called from Problem::describe_dofs(...)
virtual void describe_nodal_local_dofs (std::ostream &out, const std::string &current_string) const
Function to describe the local dofs of the element[s]. The ostream specifies the output stream to which the description is written; the string stores the currently assembled output that is ultimately written to the output stream by Data::describe_dofs(...); it is typically built up incrementally as we descend through the call hierarchy of this function when called from Problem::describe_dofs(...)
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
Overloaded version of the calculation of the local equation numbers. If the boolean argument is true then pointers to the degrees of freedom associated with each equation number are stored locally in the array Dof_pt.
Node *& node_pt (const unsigned &n)
Return a pointer to the local node n.
Node *const & node_pt (const unsigned &n) const
Return a pointer to the local node n (const version)
unsigned nnode () const
Return the number of nodes.
virtual unsigned nnode_1d () const
Return the number of nodes along one edge of the element Default is to return zero --- must be overloaded by geometric elements.
double raw_nodal_position (const unsigned &n, const unsigned &i) const
Return the i-th coordinate at local node n. Do not use the hanging node representation. NOTE: Moved to cc file because of a possible compiler bug in gcc (yes, really!). The move to the cc file avoids inlining which appears to cause problems (only) when compiled with gcc and -O3; offensive "illegal read" is in optimised-out section of code and data that is allegedly illegal is readily readable (by other means) just before this function is called so I can't really see how we could possibly be responsible for this...
double raw_nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
Return the i-th coordinate at local node n, at time level t (t=0: present; t>0: previous time level). Do not use the hanging node representation.
double raw_dnodal_position_dt (const unsigned &n, const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt at local node n. Do not use the hanging node representation.
double raw_dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
Return the i-th component of j-th derivative of nodal position: d^jx/dt^j at node n. Do not use the hanging node representation.
double raw_nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
Return the value of the k-th type of the i-th positional variable at the local node n. Do not use the hanging node representation.
double raw_nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
Return the generalised nodal position (type k, i-th variable) at previous timesteps at local node n. Do not use the hanging node representation.
double raw_dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
i-th component of time derivative (velocity) of the generalised position, dx(k,i)/dt at local node n. `Type': k; Coordinate direction: i. Do not use the hanging node representation.
double raw_dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
i-th component of j-th time derivative of the generalised position, dx(k,i)/dt at local node n. `Type': k; Coordinate direction: i. Do not use the hanging node representation.
double nodal_position (const unsigned &n, const unsigned &i) const
Return the i-th coordinate at local node n. If the node is hanging, the appropriate interpolation is handled by the position function in the Node class.
double nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
Return the i-th coordinate at local node n, at time level t (t=0: present; t>0: previous time level) Returns suitably interpolated version for hanging nodes.
double dnodal_position_dt (const unsigned &n, const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt at local node n.
double dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
Return the i-th component of j-th derivative of nodal position: d^jx/dt^j at node n.
double nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
Return the value of the k-th type of the i-th positional variable at the local node n.
double nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
Return the generalised nodal position (type k, i-th variable) at previous timesteps at local node n.
double dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
i-th component of time derivative (velocity) of the generalised position, dx(k,i)/dt at local node n. `Type': k; Coordinate direction: i.
double dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
i-th component of j-th time derivative of the generalised position, dx(k,i)/dt at local node n. `Type': k; Coordinate direction: i.
unsigned nnodal_position_type () const
Return the number of coordinate types that the element requires to interpolate the geometry between the nodes. For Lagrange elements it is 1.
bool has_hanging_nodes () const
Return boolean to indicate if any of the element's nodes are geometrically hanging.
unsigned nodal_dimension () const
Return the required Eulerian dimension of the nodes in this element.
virtual Node * construct_node (const unsigned &n)
Construct the local node n and return a pointer to the newly created node object.
virtual Node * construct_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
Construct the local node n, including storage for history values required by timestepper, and return a pointer to the newly created node object.
virtual Node * construct_boundary_node (const unsigned &n)
Construct the local node n as a boundary node; that is a node that MAY be placed on a mesh boundary and return a pointer to the newly created node object.
virtual Node * construct_boundary_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
Construct the local node n, including storage for history values required by timestepper, as a boundary node; that is a node that MAY be placed on a mesh boundary and return a pointer to the newly created node object.
int get_node_number (Node *const &node_pt) const
Return the number of the node *node_pt if this node is in the element, else return -1;.
virtual Node * get_node_at_local_coordinate (const Vector< double > &s) const
If there is a node at this local coordinate, return the pointer to the node.
double raw_nodal_value (const unsigned &n, const unsigned &i) const
Return the i-th value stored at local node n but do NOT take hanging nodes into account.
double raw_nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
Return the i-th value stored at local node n, at time level t (t=0: present; t>0 previous timesteps), but do NOT take hanging nodes into account.
double nodal_value (const unsigned &n, const unsigned &i) const
Return the i-th value stored at local node n. Produces suitably interpolated values for hanging nodes.
double nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
Return the i-th value stored at local node n, at time level t (t=0: present; t>0 previous timesteps). Produces suitably interpolated values for hanging nodes.
unsigned dim () const
Return the spatial dimension of the element, i.e. the number of local coordinates required to parametrise its geometry.
virtual ElementGeometry::ElementGeometry element_geometry () const
Return the geometry type of the element (either Q or T usually).
virtual double interpolated_x (const Vector< double > &s, const unsigned &i) const
Return FE interpolated coordinate x[i] at local coordinate s.
virtual double interpolated_x (const unsigned &t, const Vector< double > &s, const unsigned &i) const
Return FE interpolated coordinate x[i] at local coordinate s at previous timestep t (t=0: present; t>0: previous timestep)
virtual void interpolated_x (const Vector< double > &s, Vector< double > &x) const
Return FE interpolated position x[] at local coordinate s as Vector.
virtual void interpolated_x (const unsigned &t, const Vector< double > &s, Vector< double > &x) const
Return FE interpolated position x[] at local coordinate s at previous timestep t as Vector (t=0: present; t>0: previous timestep)
virtual double interpolated_dxdt (const Vector< double > &s, const unsigned &i, const unsigned &t)
Return t-th time-derivative of the i-th FE-interpolated Eulerian coordinate at local coordinate s.
virtual void interpolated_dxdt (const Vector< double > &s, const unsigned &t, Vector< double > &dxdt)
Compte t-th time-derivative of the FE-interpolated Eulerian coordinate vector at local coordinate s.
unsigned ngeom_data () const
A standard FiniteElement is fixed, so there are no geometric data when viewed in its GeomObject incarnation.
Data * geom_data_pt (const unsigned &j)
A standard FiniteElement is fixed, so there are no geometric data when viewed in its GeomObject incarnation.
void position (const Vector< double > &zeta, Vector< double > &r) const
Return the parametrised position of the FiniteElement in its incarnation as a GeomObject, r(zeta). The position is given by the Eulerian coordinate and the intrinsic coordinate (zeta) is the local coordinate of the element (s).
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
Return the parametrised position of the FiniteElement in its GeomObject incarnation: r(zeta). The position is given by the Eulerian coordinate and the intrinsic coordinate (zeta) is the local coordinate of the element (s) This version of the function returns the position as a function of time t=0: current time; t>0: previous timestep. Works for t=0 but needs to be overloaded if genuine time-dependence is required.
void dposition_dt (const Vector< double > &zeta, const unsigned &t, Vector< double > &drdt)
Return the t-th time derivative of the parametrised position of the FiniteElement in its GeomObject incarnation: $ \frac{d^{t} dr(zeta)}{d t^{t}} $. Call the t-th time derivative of the FE-interpolated Eulerian coordinate.
virtual double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
Specify the values of the "global" intrinsic coordinate, zeta, of a compound geometric object (a mesh of elements) when the element is viewied as a sub-geometric object. The default assumption is that the element will be treated as a sub-geometric object in a bulk Mesh of other elements (geometric objects). The "global" coordinate of the compound geometric object is simply the Eulerian coordinate, x. The second default assumption is that the coordinate zeta will be stored at the nodes and interpolated using the shape functions of the element. This function returns the value of zeta stored at local node n, where k is the type of coordinate and i is the coordinate direction. The function is virtual so that it can be overloaded by different types of element: FaceElements and SolidFiniteElements.
void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
Calculate the interpolated value of zeta, the intrinsic coordinate of the element when viewed as a compound geometric object within a Mesh as a function of the local coordinate of the element, s. The default assumption is the zeta is interpolated using the shape functions of the element with the values given by zeta_nodal(). A MacroElement representation of the intrinsic coordinate parametrised by the local coordinate s is used if available. Choosing the MacroElement representation of zeta (Eulerian x by default) allows a correspondence to be established between elements on different Meshes covering the same curvilinear domain in cases where one element is much coarser than the other.
void locate_zeta (const Vector< double > &zeta, GeomObject *&geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
For a given value of zeta, the "global" intrinsic coordinate of a mesh of FiniteElements represented as a compound geometric object, find the local coordinate in this element that corresponds to the requested value of zeta. If zeta cannot be located in this element, geom_object_pt is set to NULL. If zeta is located in this element, we return its "this" pointer. By default don't use any value passed in to the local coordinate s as the initial guess in the Newton method.
virtual void node_update ()
Update the positions of all nodes in the element using each node update function. The default implementation may be overloaded so that more efficient versions can be written.
virtual void identify_geometric_data (std::set< Data * > &geometric_data_pt)
The purpose of this function is to identify all Data objects that affect the elements' geometry. This function is implemented as an empty virtual function since it can only be implemented in conjunction with a node-update strategy. A specific implementation is provided in the ElementWithMovingNodes class.
virtual double s_min () const
Min value of local coordinate.
virtual double s_max () const
Max. value of local coordinate.
double size () const
Calculate the size of the element (length, area, volume,...) in Eulerian computational coordinates. Use suitably overloaded compute_physical_size() function to compute the actual size (taking into account factors such as 2pi or radii the integrand) -- such function can only be implemented on an equation-by-equation basis.
virtual double compute_physical_size () const
Broken virtual function to compute the actual size (taking into account factors such as 2pi or radii the integrand) -- such function can only be implemented on an equation-by-equation basis.
void point_output (std::ostream &outfile, const Vector< double > &s)
Output solution (as defined by point_output_data()) at local cordinates s.
virtual unsigned nplot_points_paraview (const unsigned &nplot) const
Return the number of actual plot points for paraview plot with parameter nplot. Broken virtual; can be overloaded in specific elements.
virtual unsigned nsub_elements_paraview (const unsigned &nplot) const
Return the number of local sub-elements for paraview plot with parameter nplot. Broken virtual; can be overloaded in specific elements.
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
Paraview output -- this outputs the coordinates at the plot points (for parameter nplot) to specified output file.
virtual void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
Fill in the offset information for paraview plot. Broken virtual. Needs to be implemented for each new geometric element type; see http://www.vtk.org/VTK/img/file-formats.pdf.
virtual void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
Return the paraview element type. Broken virtual. Needs to be implemented for each new geometric element type; see http://www.vtk.org/VTK/img/file-formats.pdf.
virtual void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
Return the offsets for the paraview sub-elements. Broken virtual. Needs to be implemented for each new geometric element type; see http://www.vtk.org/VTK/img/file-formats.pdf.
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
Write values of the i-th scalar field at the plot points. Broken virtual. Needs to be implemented for each new specific element type.
virtual void output (const unsigned &t, std::ostream &outfile, const unsigned &n_plot) const
Output the element data at time step t. This is const because it is newly added and so can be done easily. Really all the output(...) functions should be const!
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, const SolutionFunctorBase &exact_soln) const
Output a time-dependent exact solution over the element.
virtual void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &shifted_to_interior=false) const
Get cector of local coordinates of plot point i (when plotting nplot points in each "coordinate direction"). Generally these plot points will be uniformly spaced across the element. The optional final boolean flag (default: false) allows them to be shifted inwards to avoid duplication of plot point points between elements -- useful when they are used in locate_zeta, say.
virtual std::string tecplot_zone_string (const unsigned &nplot) const
Return string for tecplot zone header (when plotting nplot points in each "coordinate direction")
virtual void write_tecplot_zone_footer (std::ostream &outfile, const unsigned &nplot) const
Add tecplot zone "footer" to output stream (when plotting nplot points in each "coordinate direction"). Empty by default -- can be used, e.g., to add FE connectivity lists to elements that need it.
virtual void write_tecplot_zone_footer (FILE *file_pt, const unsigned &nplot) const
Add tecplot zone "footer" to C-style output. (when plotting nplot points in each "coordinate direction"). Empty by default -- can be used, e.g., to add FE connectivity lists to elements that need it.
virtual unsigned nplot_points (const unsigned &nplot) const
Return total number of plot points (when plotting nplot points in each "coordinate direction")
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
Given the exact solution $ {\bf f}({\bf x}) $ this function calculates the norm of the error and that of the exact solution. Version with vectors of norms and errors so that different variables' norms and errors can be returned individually.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
Given the exact solution $ {\bf f}({\bf x}) $ this function calculates the norm of the error and that of the exact solution. Version with vectors of norms and errors so that different variables' norms and errors can be returned individually.
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
Plot the error when compared against a given exact solution $ {\bf f}({\bf x}) $. Also calculates the norm of the error and that of the exact solution. The version with vectors of norms and errors so that different variables' norms and errors can be returned individually.
virtual void compute_abs_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error)
Plot the error when compared against a given exact solution $ {\bf f}({\bf x}) $. Also calculates the maximum absolute error.
void integrate_fct (FiniteElement::SteadyExactSolutionFctPt integrand_fct_pt, Vector< double > &integral)
Evaluate integral of a Vector-valued function $ {\bf f}({\bf x}) $ over the element.
void integrate_fct (FiniteElement::UnsteadyExactSolutionFctPt integrand_fct_pt, const double &time, Vector< double > &integral)
Evaluate integral of a Vector-valued, time-dependent function $ {\bf f}(t,{\bf x}) $ over the element.
virtual void build_face_element (const int &face_index, FaceElement *face_element_pt)
Function for building a lower dimensional FaceElement on the specified face of the FiniteElement. The arguments are the index of the face, an integer whose value depends on the particular element type, and a pointer to the FaceElement.
virtual unsigned self_test ()
Self-test: Check inversion of element & do self-test for GeneralisedElement. Return 0 if OK.
virtual unsigned get_bulk_node_number (const int &face_index, const unsigned &i) const
Get the number of the ith node on face face_index (in the bulk node vector).
virtual int face_outer_unit_normal_sign (const int &face_index) const
Get the sign of the outer unit normal on the face given by face_index.
virtual unsigned nnode_on_face () const
void face_node_number_error_check (const unsigned &i) const
Range check for face node numbers.
virtual CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt (const int &face_index) const
Get a pointer to the function mapping face coordinates to bulk coordinates.
virtual BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt (const int &face_index) const
Get a pointer to the derivative of the mapping from face to bulk coordinates.
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement() GeneralisedElement (const GeneralisedElement &)=delete
Constructor: Initialise all pointers and all values to zero.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
Return the global equation number corresponding to the ieqn_local-th local equation number.
int local_eqn_number (const unsigned long &ieqn_global) const
Return the local equation number corresponding to the ieqn_global-th global equation number. Returns minus one (-1) if there is no local degree of freedom corresponding to the chosen global equation number.
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
Add a (pointer to an) external data object to the element and return its index (i.e. the index required to obtain it from the access function external_data_pt(...). The optional boolean flag indicates whether the data should be included in the general finite-difference loop when calculating the jacobian. The default value is true, i.e. the data will be included in the finite-differencing.
bool external_data_fd (const unsigned &i) const
Return the status of the boolean flag indicating whether the external data is included in the finite difference loop.
void exclude_external_data_fd (const unsigned &i)
Set the boolean flag to exclude the external datum from the the finite difference loop when computing the jacobian matrix.
void include_external_data_fd (const unsigned &i)
Set the boolean flag to include the external datum in the the finite difference loop when computing the jacobian matrix.
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set the timestepper associated with the i-th internal data object.
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
Assign the global equation numbers to the internal Data. The arguments are the current highest global equation number (which will be incremented) and a Vector of pointers to the global variables (to which any unpinned values in the internal Data are added).
void describe_dofs (std::ostream &out, const std::string &current_string) const
Function to describe the dofs of the element. The ostream specifies the output stream to which the description is written; the string stores the currently assembled output that is ultimately written to the output stream by Data::describe_dofs(...); it is typically built up incrementally as we descend through the call hierarchy of this function when called from Problem::describe_dofs(...)
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
Add pointers to the internal data values to map indexed by the global equation number.
void add_internal_data_values_to_vector (Vector< double > &vector_of_values)
Add all internal data and time history values to the vector in the internal storage order.
void read_internal_data_values_from_vector (const Vector< double > &vector_of_values, unsigned &index)
Read all internal data and time history values from the vector starting from index. On return the index will be set to the value at the end of the data that has been read in.
void add_internal_eqn_numbers_to_vector (Vector< long > &vector_of_eqn_numbers)
Add all equation numbers associated with internal data to the vector in the internal storage order.
void read_internal_eqn_numbers_from_vector (const Vector< long > &vector_of_eqn_numbers, unsigned &index)
Read all equation numbers associated with internal data from the vector starting from index. On return the index will be set to the value at the end of the data that has been read in.
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
Setup the arrays of local equation numbers for the element. If the optional boolean argument is true, then pointers to the associated degrees of freedom are stored locally in the array Dof_pt.
virtual void complete_setup_of_dependencies ()
Complete the setup of any additional dependencies that the element may have. Empty virtual function that may be overloaded for specific derived elements. Used, e.g., for elements with algebraic node update functions to determine the "geometric Data", i.e. the Data that affects the element's shape. This function is called (for all elements) at the very beginning of the equation numbering procedure to ensure that all dependencies are accounted for.
virtual void get_residuals (Vector< double > &residuals)
Calculate the vector of residuals of the equations in the element. By default initialise the vector to zero and then call the fill_in_contribution_to_residuals() function. Note that this entire function can be overloaded if desired.
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Calculate the elemental Jacobian matrix "d equation / d variable".
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
Calculate the residuals and the elemental "mass" matrix, the matrix that multiplies the time derivative terms in a problem.
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
Calculate the residuals and jacobian and elemental "mass" matrix, the matrix that multiplies the time derivative terms.
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
Calculate the derivatives of the residuals with respect to a parameter.
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
Calculate the derivatives of the elemental Jacobian matrix and residuals with respect to a parameter.
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
Calculate the derivatives of the elemental Jacobian matrix mass matrix and residuals with respect to a parameter.
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
Calculate the product of the Hessian (derivative of Jacobian with respect to all variables) an eigenvector, Y, and other specified vectors, C (d(J_{ij})/d u_{k}) Y_{j} C_{k}.
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned > > const &history_index, Vector< double > &inner_product)
Return the vector of inner product of the given pairs of history values.
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double > > &inner_product_vector)
Compute the vectors that when taken as a dot product with other history values give the inner product over the element.
virtual void compute_norm (double &norm)
Compute norm of solution -- broken virtual can be overloaded by element writer to implement whatever norm is desired for the specific element.
void set_halo (const unsigned &non_halo_proc_ID)
Label the element as halo and specify processor that holds non-halo counterpart.
void set_nonhalo ()
Label the element as not being a halo.
bool is_halo () const
Is this element a halo?
int non_halo_proc_ID ()
ID of processor ID that holds non-halo counterpart of halo element; negative if not a halo.
void set_must_be_kept_as_halo ()
Insist that this element be kept as a halo element during a distribute?
void unset_must_be_kept_as_halo ()
Do not insist that this element be kept as a halo element during distribution.
bool must_be_kept_as_halo () const
Test whether the element must be kept as a halo element.
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
Constructor: Pass dimension of geometric object (# of Eulerian coords = # of Lagrangian coords; no time history available/needed)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
Constructor: pass # of Eulerian and Lagrangian coordinates. No time history available/needed.
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
Constructor: pass # of Eulerian and Lagrangian coordinates and pointer to time-stepper which is used to handle the position at previous timesteps and allows the evaluation of veloc/acceleration etc. in cases where the GeomData varies with time.
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
Access function for pointer to time stepper: Null if object is not time-dependent.
TimeStepper * time_stepper_pt () const
Access function for pointer to time stepper: Null if object is not time-dependent. Const version.
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
Parametrised position on object: r(zeta). Evaluated at the continuous time value, t.
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
Derivative of position Vector w.r.t. to coordinates: $ \frac{dR_i}{d \zeta_\alpha}$ = drdzeta(alpha,i). Evaluated at current time.
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
2nd derivative of position Vector w.r.t. to coordinates: $ \frac{d^2R_i}{d \zeta_\alpha d \zeta_\beta}$ = ddrdzeta(alpha,beta,i). Evaluated at current time.
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Posn Vector and its 1st & 2nd derivatives w.r.t. to coordinates: $ \frac{dR_i}{d \zeta_\alpha}$ = drdzeta(alpha,i). $ \frac{d^2R_i}{d \zeta_\alpha d \zeta_\beta}$ = ddrdzeta(alpha,beta,i). Evaluated at current time.
Public Member Functions inherited from oomph::TemplateFreeSpaceTimeNavierStokesEquationsBase
TemplateFreeSpaceTimeNavierStokesEquationsBase ()
Constructor (empty)
virtual ~TemplateFreeSpaceTimeNavierStokesEquationsBase ()
Virtual destructor (empty)
TemplateFreeSpaceTimeNavierStokesEquationsBase ()
Constructor (empty)
virtual ~TemplateFreeSpaceTimeNavierStokesEquationsBase ()
Virtual destructor (empty)
TemplateFreeSpaceTimeNavierStokesEquationsBase ()
Constructor (empty)
virtual ~TemplateFreeSpaceTimeNavierStokesEquationsBase ()
Virtual destructor (empty)
Public Member Functions inherited from oomph::NavierStokesElementWithDiagonalMassMatrices
NavierStokesElementWithDiagonalMassMatrices ()
Empty constructor.
virtual ~NavierStokesElementWithDiagonalMassMatrices ()
Virtual destructor.
NavierStokesElementWithDiagonalMassMatrices (const NavierStokesElementWithDiagonalMassMatrices &)=delete
Broken copy constructor.
void operator= (const NavierStokesElementWithDiagonalMassMatrices &)=delete
Broken assignment operator.
Public Member Functions inherited from oomph::RefineableSpaceTimeNavierStokesEquations< DIM >
RefineableSpaceTimeNavierStokesEquations ()
Constructor.
void get_pressure_and_velocity_mass_matrix_diagonal (Vector< double > &press_mass_diag, Vector< double > &veloc_mass_diag, const unsigned &which_one=0)
Compute the diagonal of the velocity/pressure mass matrices. If which one=0, both are computed, otherwise only the pressure (which_one=1) or the velocity mass matrix (which_one=2 -- the LSC version of the preconditioner only needs that one)
unsigned num_Z2_flux_terms ()
Number of 'flux' terms for Z2 error estimation.
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
Get 'flux' for Z2 error recovery: Upper triangular entries in strain rate tensor.
void further_build ()
Further build, pass the pointers down to the sons.
void dinterpolated_u_nst_ddata (const Vector< double > &s, const unsigned &i, Vector< double > &du_ddata, Vector< unsigned > &global_eqn_number)
Compute the derivatives of the i-th component of velocity at point s with respect to all data that can affect its value. In addition, return the global equation numbers corresponding to the data. Overload the non-refineable version to take account of hanging node information.
RefineableSpaceTimeNavierStokesEquations ()
Constructor.
void get_pressure_and_velocity_mass_matrix_diagonal (Vector< double > &press_mass_diag, Vector< double > &veloc_mass_diag, const unsigned &which_one=0)
Compute the diagonal of the velocity/pressure mass matrices. If which one=0, both are computed, otherwise only the pressure (which_one=1) or the velocity mass matrix (which_one=2 -- the LSC version of the preconditioner only needs that one)
unsigned num_Z2_flux_terms ()
Number of 'flux' terms for Z2 error estimation.
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
Get 'flux' for Z2 error recovery: Upper triangular entries in strain rate tensor.
void further_build ()
Further build, pass the pointers down to the sons.
void dinterpolated_u_nst_ddata (const Vector< double > &s, const unsigned &i, Vector< double > &du_ddata, Vector< unsigned > &global_eqn_number)
Compute the derivatives of the i-th component of velocity at point s with respect to all data that can affect its value. In addition, return the global equation numbers corresponding to the data. Overload the non-refineable version to take account of hanging node information.
RefineableSpaceTimeNavierStokesEquations ()
Constructor.
void get_pressure_and_velocity_mass_matrix_diagonal (Vector< double > &press_mass_diag, Vector< double > &veloc_mass_diag, const unsigned &which_one=0)
Compute the diagonal of the velocity/pressure mass matrices. If which one=0, both are computed, otherwise only the pressure (which_one=1) or the velocity mass matrix (which_one=2 -- the LSC version of the preconditioner only needs that one)
unsigned num_Z2_flux_terms ()
Number of 'flux' terms for Z2 error estimation.
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
Get 'flux' for Z2 error recovery: Upper triangular entries in strain rate tensor.
void further_build ()
Further build, pass the pointers down to the sons.
void dinterpolated_u_nst_ddata (const Vector< double > &s, const unsigned &i, Vector< double > &du_ddata, Vector< unsigned > &global_eqn_number)
Compute the derivatives of the i-th component of velocity at point s with respect to all data that can affect its value. In addition, return the global equation numbers corresponding to the data. Overload the non-refineable version to take account of hanging node information.
Public Member Functions inherited from oomph::RefineableElement
RefineableElement ()
Constructor, calls the FiniteElement constructor and initialises the member data.
virtual ~RefineableElement ()
Destructor, delete the allocated storage for the hanging equations.
RefineableElement (const RefineableElement &)=delete
Broken copy constructor.
void operator= (const RefineableElement &)=delete
Broken assignment operator.
Tree * tree_pt ()
Access function: Pointer to quadtree representation of this element.
void set_tree_pt (Tree *my_tree_pt)
Set pointer to quadtree representation of this element.
virtual unsigned required_nsons () const
Set the number of sons that can be constructed by the element The default is none.
bool refinement_is_enabled ()
Flag to indicate suppression of any refinement.
void disable_refinement ()
Suppress of any refinement for this element.
void enable_refinement ()
Emnable refinement for this element.
template<class ELEMENT >
void split (Vector< ELEMENT * > &son_pt) const
Split the element into the number of sons to be constructed and return a vector of pointers to the sons. Elements are allocated, but they are not given any properties. The refinement level of the sons is one higher than that of the father elemern.
int local_hang_eqn (Node *const &node_pt, const unsigned &i)
Access function that returns the local equation number for the hanging node variables (values stored at master nodes). The local equation number corresponds to the i-th unknown stored at the node addressed by node_pt.
virtual void build (Mesh *&mesh_pt, Vector< Node * > &new_node_pt, bool &was_already_built, std::ofstream &new_nodes_file)=0
Interface to function that builds the element: i.e. construct the nodes, assign their positions, apply boundary conditions, etc. The required procedures depend on the geometrical type of the element and must be implemented in specific refineable elements. Any new nodes created during the build process are returned in the vector new_node_pt.
void set_refinement_level (const int &refine_level)
Set the refinement level.
unsigned refinement_level () const
Return the Refinement level.
void select_for_refinement ()
Select the element for refinement.
void deselect_for_refinement ()
Deselect the element for refinement.
void select_sons_for_unrefinement ()
Unrefinement will be performed by merging the four sons of this element.
void deselect_sons_for_unrefinement ()
No unrefinement will be performed by merging the four sons of this element.
bool to_be_refined ()
Has the element been selected for refinement?
bool sons_to_be_unrefined ()
Has the element been selected for unrefinement?
virtual void unbuild ()
Unbuild the element, i.e. mark the nodes that were created during its creation for possible deletion.
virtual void deactivate_element ()
Final operations that must be performed when the element is no longer active in the mesh, but still resident in the QuadTree.
virtual bool nodes_built ()
Return true if all the nodes have been built, false if not.
long number () const
Element number (for debugging/plotting)
void set_number (const long &mynumber)
Set element number (for debugging/plotting)
virtual void check_integrity (double &max_error)=0
Check the integrity of the element: Continuity of positions values, etc. Essentially, check that the approximation of the functions is consistent when viewed from both sides of the element boundaries Must be overloaded for each different geometric element.
void identify_field_data_for_interactions (std::set< std::pair< Data *, unsigned > > &paired_field_data)
The purpose of this function is to identify all possible Data that can affect the fields interpolated by the FiniteElement. This must be overloaded to include data from any hanging nodes correctly.
void assign_nodal_local_eqn_numbers (const bool &store_local_dof_pt)
Overload the function that assigns local equation numbers for the Data stored at the nodes so that hanging data is taken into account.
virtual RefineableElement * root_element_pt ()
Pointer to the root element in refinement hierarchy (must be implemented in specific elements that do refinement via tree-like refinement structure. Here we provide a default implementation that is appropriate for cases where tree-like refinement doesn't exist or if the element doesn't have root in that tree (i.e. if it's a root itself): We return "this".
virtual RefineableElement * father_element_pt () const
Return a pointer to the father element.
void get_father_at_refinement_level (unsigned &refinement_level, RefineableElement *&father_at_reflevel_pt)
Return a pointer to the "father" element at the specified refinement level.
virtual void initial_setup (Tree *const &adopted_father_pt=0, const unsigned &initial_p_order=0)
Initial setup of the element: e.g. set the appropriate internal p-order. If an adopted father is specified, information from this is used instead of using the father found from the tree.
virtual void pre_build (Mesh *&mesh_pt, Vector< Node * > &new_node_pt)
Pre-build the element.
virtual void setup_hanging_nodes (Vector< std::ofstream * > &output_stream)
Mark up any hanging nodes that arise as a result of non-uniform refinement. Any hanging nodes will be documented in files addressed by the streams in the vector output_stream, if the streams are open.
unsigned nshape_controlling_nodes ()
Number of shape-controlling nodes = the number of non-hanging nodes plus the number of master nodes associated with hanging nodes.
std::map< Node *, unsigned > shape_controlling_node_lookup ()
Return lookup scheme for unique number associated with any of the nodes that actively control the shape of the element (i.e. they are either non-hanging nodes of this element or master nodes of hanging nodes.
Public Member Functions inherited from oomph::ElementWithZ2ErrorEstimator
ElementWithZ2ErrorEstimator ()
Default empty constructor.
ElementWithZ2ErrorEstimator (const ElementWithZ2ErrorEstimator &)=delete
Broken copy constructor.
void operator= (const ElementWithZ2ErrorEstimator &)=delete
Broken assignment operator.
virtual unsigned ncompound_fluxes ()
A stuitable error estimator for a multi-physics elements may require one Z2 error estimate for each field (e.g. velocity and temperature in a fluid convection problem). It is assumed that these error estimates will each use selected flux terms. The number of compound fluxes returns the number of such combinations of the flux terms. Default value is one and all flux terms are combined with equal weight.
virtual void compute_exact_Z2_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_flux_pt, double &error, double &norm)
Plot the error when compared against a given exact flux. Also calculates the norm of the error and that of the exact flux.
virtual void get_Z2_compound_flux_indices (Vector< unsigned > &flux_index)
Return the compound flux index of each flux component The default (do nothing behaviour) will mean that all indices remain at the default value zero.
virtual double geometric_jacobian (const Vector< double > &x)
Return the geometric jacobian (should be overloaded in cylindrical and spherical geometries). Default value one is suitable for Cartesian coordinates.
Public Member Functions inherited from oomph::RefineableQElement< DIM+1 >
RefineableQElement ()
Empty constuctor.
Private Member Functions
void unpin_elemental_pressure_dofs ()
Unpin all pressure dofs.
void pin_elemental_redundant_nodal_pressure_dofs ()
Pin all nodal pressure dofs that are not required.
void unpin_elemental_pressure_dofs ()
Unpin all pressure dofs.
void pin_elemental_redundant_nodal_pressure_dofs ()
Pin all nodal pressure dofs that are not required.
void unpin_elemental_pressure_dofs ()
Unpin all pressure dofs.
void pin_elemental_redundant_nodal_pressure_dofs ()
Pin all nodal pressure dofs that are not required.
Additional Inherited Members
Public Types inherited from oomph::SpaceTimeNavierStokesEquations< DIM >
typedef void(* NavierStokesBodyForceFctPt) (const double &time, const Vector< double > &x, Vector< double > &body_force)
Function pointer to body force function fct(t,x,f(x)) x is a Vector!
typedef double(* NavierStokesSourceFctPt) (const double &time, const Vector< double > &x)
Function pointer to source function fct(t,x) (x is a Vector!)
typedef double(* NavierStokesPressureAdvDiffSourceFctPt) (const Vector< double > &x)
Function pointer to source function fct(x) for the pressure advection diffusion equation (only used during validation!). x is a Vector!
typedef void(* NavierStokesBodyForceFctPt) (const double &time, const Vector< double > &x, Vector< double > &body_force)
Function pointer to body force function fct(t,x,f(x)) x is a Vector!
typedef double(* NavierStokesSourceFctPt) (const double &time, const Vector< double > &x)
Function pointer to source function fct(t,x) (x is a Vector!)
typedef double(* NavierStokesPressureAdvDiffSourceFctPt) (const Vector< double > &x)
Function pointer to source function fct(x) for the pressure advection diffusion equation (only used during validation!). x is a Vector!
typedef void(* NavierStokesBodyForceFctPt) (const double &time, const Vector< double > &x, Vector< double > &body_force)
Function pointer to body force function fct(t,x,f(x)) x is a Vector!
typedef double(* NavierStokesSourceFctPt) (const double &time, const Vector< double > &x)
Function pointer to source function fct(t,x) (x is a Vector!)
typedef double(* NavierStokesPressureAdvDiffSourceFctPt) (const Vector< double > &x)
Function pointer to source function fct(x) for the pressure advection diffusion equation (only used during validation!). x is a Vector!
Public Types inherited from oomph::FiniteElement
typedef void(* SteadyExactSolutionFctPt) (const Vector< double > &, Vector< double > &)
Function pointer for function that computes vector-valued steady "exact solution" $ {\bf f}({\bf x}) $ as $ \mbox{\tt fct}({\bf x}, {\bf f}) $.
typedef void(* UnsteadyExactSolutionFctPt) (const double &, const Vector< double > &, Vector< double > &)
Function pointer for function that computes Vector-valued time-dependent function $ {\bf f}(t,{\bf x}) $ as $ \mbox{\tt fct}(t, {\bf x}, {\bf f}) $.
Static Public Member Functions inherited from oomph::RefineableSpaceTimeNavierStokesEquations< DIM >
static void pin_redundant_nodal_pressures (const Vector< GeneralisedElement * > &element_pt)
Loop over all elements in Vector (which typically contains all the elements in a fluid mesh) and pin the nodal pressure degrees of freedom that are not being used. Function uses the member function.
static void unpin_all_pressure_dofs (const Vector< GeneralisedElement * > &element_pt)
Unpin all pressure dofs in elements listed in vector.
static void pin_redundant_nodal_pressures (const Vector< GeneralisedElement * > &element_pt)
Loop over all elements in Vector (which typically contains all the elements in a fluid mesh) and pin the nodal pressure degrees of freedom that are not being used. Function uses the member function.
static void unpin_all_pressure_dofs (const Vector< GeneralisedElement * > &element_pt)
Unpin all pressure dofs in elements listed in vector.
static void pin_redundant_nodal_pressures (const Vector< GeneralisedElement * > &element_pt)
Loop over all elements in Vector (which typically contains all the elements in a fluid mesh) and pin the nodal pressure degrees of freedom that are not being used. Function uses the member function.
static void unpin_all_pressure_dofs (const Vector< GeneralisedElement * > &element_pt)
Unpin all pressure dofs in elements listed in vector.
Static Public Member Functions inherited from oomph::RefineableElement
static double & max_integrity_tolerance ()
Max. allowed discrepancy in element integrity check.
Static Public Attributes inherited from oomph::SpaceTimeNavierStokesEquations< DIM >
static Vector< double > Gamma
Vector to decide whether the stress-divergence form is used or not N.B. This needs to be public so that the intel compiler gets things correct somehow the access function messes things up when going to refineable Navier-Stokes.
Static Public Attributes inherited from oomph::FiniteElement
static double Tolerance_for_singular_jacobian = 1.0e-16
Tolerance below which the jacobian is considered singular.
static bool Accept_negative_jacobian = false
Boolean that if set to true allows a negative jacobian in the transform between global and local coordinates (negative surface area = left-handed coordinate system).
static bool Suppress_output_while_checking_for_inverted_elements
Static boolean to suppress output while checking for inverted elements.
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_any_repeated_data = false
Static boolean to suppress warnings about repeated data. Defaults to false.
static bool Suppress_warning_about_repeated_internal_data
Static boolean to suppress warnings about repeated internal data. Defaults to false.
static bool Suppress_warning_about_repeated_external_data = true
Static boolean to suppress warnings about repeated external data. Defaults to true.
static double Default_fd_jacobian_step = 1.0e-8
Double used for the default finite difference step in elemental jacobian calculations.
Protected Member Functions inherited from oomph::QTaylorHoodSpaceTimeElement< DIM >
double dshape_and_dtest_eulerian_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping (J). Also compute derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
double dpshape_eulerian (const Vector< double > &s, Shape &ppsi, DShape &dppsidx) const
Pressure shape functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry). Return Jacobian of mapping between local and global coordinates.
double dptest_eulerian (const Vector< double > &s, Shape &ptest, DShape &dptestdx) const
Pressure test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry). Return Jacobian of mapping between local and global coordinates.
double dpshape_and_dptest_eulerian_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const
Pressure shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry). Return Jacobian of mapping between local and global coordinates.
double dshape_and_dtest_eulerian_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping (J). Also compute derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
double dpshape_eulerian (const Vector< double > &s, Shape &ppsi, DShape &dppsidx) const
Pressure shape functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry). Return Jacobian of mapping between local and global coordinates.
double dptest_eulerian (const Vector< double > &s, Shape &ptest, DShape &dptestdx) const
Pressure test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry). Return Jacobian of mapping between local and global coordinates.
double dpshape_and_dptest_eulerian_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const
Pressure shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry). Return Jacobian of mapping between local and global coordinates.
double dshape_and_dtest_eulerian_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping (J). Also compute derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
double dpshape_and_dptest_eulerian_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const
Pressure shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry). Return Jacobian of mapping between local and global coordinates.
const unsigned Pconv [12]
double dpshape_eulerian (const Vector< double > &s, Shape &ppsi, DShape &dppsidx) const
2D (in space): Pressure shape and test functions and derivs w.r.t. to Eulerian coordinates. Return Jacobian of mapping between local and global coordinates.
double dptest_eulerian (const Vector< double > &s, Shape &ptest, DShape &dptestdx) const
2D (in space): Pressure shape and test functions and derivs w.r.t. to Eulerian coordinates. Return Jacobian of mapping between local and global coordinates.
double dpshape_and_dptest_eulerian_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const
2D (in space): Pressure shape and test functions and derivs w.r.t. to Eulerian coordinates. Return Jacobian of mapping between local and global coordinates.
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
2D (in space): Define the shape functions (psi) and test functions (test) and their derivatives w.r.t. global coordinates (dpsidx and dtestdx) and return Jacobian of mapping (J). Additionally compute the derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
const unsigned Pconv [8]
double dpshape_eulerian (const Vector< double > &s, Shape &ppsi, DShape &dppsidx) const
2D (in space): Pressure shape and test functions and derivs w.r.t. to Eulerian coordinates. Return Jacobian of mapping between local and global coordinates.
double dptest_eulerian (const Vector< double > &s, Shape &ptest, DShape &dptestdx) const
2D (in space): Pressure shape and test functions and derivs w.r.t. to Eulerian coordinates. Return Jacobian of mapping between local and global coordinates.
double dpshape_and_dptest_eulerian_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const
2D (in space): Pressure shape and test functions and derivs w.r.t. to Eulerian coordinates. Return Jacobian of mapping between local and global coordinates.
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
2D (in space): Define the shape functions (psi) and test functions (test) and their derivatives w.r.t. global coordinates (dpsidx and dtestdx) and return Jacobian of mapping (J). Additionally compute the derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
const unsigned Pconv [8]
double dpshape_and_dptest_eulerian_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const
2D (in space): Pressure shape and test functions and derivs w.r.t. to Eulerian coordinates. Return Jacobian of mapping between local and global coordinates.
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
2D (in space): Define the shape functions (psi) and test functions (test) and their derivatives w.r.t. global coordinates (dpsidx and dtestdx) and return Jacobian of mapping (J). Additionally compute the derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
Protected Member Functions inherited from oomph::SpaceTimeNavierStokesEquations< DIM >
virtual void get_body_force_nst (const double &time, const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, Vector< double > &result)
Calculate the body force at a given time and local and/or Eulerian position. This function is virtual so that it can be overloaded in multi-physics elements where the body force might depend on another variable.
virtual void get_body_force_gradient_nst (const double &time, const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, DenseMatrix< double > &d_body_force_dx)
Get gradient of body force term at (Eulerian) position x. This function is virtual to allow overloading in multi-physics problems where the strength of the source function might be determined by another system of equations. Computed via function pointer (if set) or by finite differencing (default)
virtual double get_source_nst (const double &time, const unsigned &ipt, const Vector< double > &x)
Calculate the source fct at a given time and Eulerian position.
virtual void get_source_gradient_nst (const double &time, const unsigned &ipt, const Vector< double > &x, Vector< double > &gradient)
Get gradient of source term at (Eulerian) position x. This function is virtual to allow overloading in multi-physics problems where the strength of the source function might be determined by another system of equations. Computed via function pointer (if set) or by finite differencing (default)
virtual void fill_in_generic_dresidual_contribution_nst (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam, const unsigned &flag)
Compute the derivatives of the residuals for the Navier-Stokes equations with respect to a parameter Flag=1 (or 0): do (or don't) compute the Jacobian as well. Flag=2: Fill in mass matrix too.
void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
Compute the hessian tensor vector products required to perform continuation of bifurcations analytically.
virtual void get_body_force_nst (const double &time, const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, Vector< double > &result)
Calculate the body force at a given time and local and/or Eulerian position. This function is virtual so that it can be overloaded in multi-physics elements where the body force might depend on another variable.
virtual void get_body_force_gradient_nst (const double &time, const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, DenseMatrix< double > &d_body_force_dx)
Get gradient of body force term at (Eulerian) position x. This function is virtual to allow overloading in multi-physics problems where the strength of the source function might be determined by another system of equations. Computed via function pointer (if set) or by finite differencing (default)
virtual double get_source_nst (const double &time, const unsigned &ipt, const Vector< double > &x)
Calculate the source fct at a given time and Eulerian position.
virtual void get_source_gradient_nst (const double &time, const unsigned &ipt, const Vector< double > &x, Vector< double > &gradient)
Get gradient of source term at (Eulerian) position x. This function is virtual to allow overloading in multi-physics problems where the strength of the source function might be determined by another system of equations. Computed via function pointer (if set) or by finite differencing (default)
virtual void fill_in_generic_dresidual_contribution_nst (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam, const unsigned &flag)
Compute the derivatives of the residuals for the Navier-Stokes equations with respect to a parameter Flag=1 (or 0): do (or don't) compute the Jacobian as well. Flag=2: Fill in mass matrix too.
void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
Compute the hessian tensor vector products required to perform continuation of bifurcations analytically.
virtual void get_body_force_nst (const double &time, const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, Vector< double > &result)
Calculate the body force at a given time and local and/or Eulerian position. This function is virtual so that it can be overloaded in multi-physics elements where the body force might depend on another variable.
virtual void get_body_force_gradient_nst (const double &time, const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, DenseMatrix< double > &d_body_force_dx)
Get gradient of body force term at (Eulerian) position x. This function is virtual to allow overloading in multi-physics problems where the strength of the source function might be determined by another system of equations. Computed via function pointer (if set) or by finite differencing (default)
virtual double get_source_nst (const double &time, const unsigned &ipt, const Vector< double > &x)
Calculate the source fct at a given time and Eulerian position.
virtual void get_source_gradient_nst (const double &time, const unsigned &ipt, const Vector< double > &x, Vector< double > &gradient)
Get gradient of source term at (Eulerian) position x. This function is virtual to allow overloading in multi-physics problems where the strength of the source function might be determined by another system of equations. Computed via function pointer (if set) or by finite differencing (default)
virtual void fill_in_generic_dresidual_contribution_nst (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam, const unsigned &flag)
Compute the derivatives of the residuals for the Navier-Stokes equations with respect to a parameter Flag=1 (or 0): do (or don't) compute the Jacobian as well. Flag=2: Fill in mass matrix too.
void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
Compute the hessian tensor vector products required to perform continuation of bifurcations analytically.
Protected Member Functions inherited from oomph::FiniteElement
template<unsigned DIM>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Take the matrix passed as jacobian and return its inverse in inverse_jacobian. This function is templated by the dimension of the element because matrix inversion cannot be written efficiently in a generic manner.
virtual double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
A template-free interface that takes the matrix passed as jacobian and return its inverse in inverse_jacobian. By default the function will use the dimension of the element to call the correct invert_jacobian(..) function. This should be overloaded for efficiency (removal of a switch statement) in specific elements.
virtual double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Calculate the mapping from local to Eulerian coordinates, given the derivatives of the shape functions w.r.t. local coordinates. Returns the determinant of the jacobian, the jacobian and inverse jacobian.
double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
Calculate the mapping from local to Eulerian coordinates, given the derivatives of the shape functions w.r.t. local coordinates, Return only the determinant of the jacobian and the inverse of the mapping (ds/dx).
virtual void dJ_eulerian_dnodal_coordinates (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
A template-free interface that calculates the derivative of the jacobian of a mapping with respect to the nodal coordinates X_ij. To do this it requires the jacobian matrix and the derivatives of the shape functions w.r.t. the local coordinates. By default the function will use the dimension of the element to call the correct dJ_eulerian_dnodal_coordinates_templated_helper(..) function. This should be overloaded for efficiency (removal of a switch statement) in specific elements.
template<unsigned DIM>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
Calculate the derivative of the jacobian of a mapping with respect to the nodal coordinates X_ij using the jacobian matrix and the derivatives of the shape functions w.r.t. the local coordinates. This function is templated by the dimension of the element.
virtual void d_dshape_eulerian_dnodal_coordinates (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
A template-free interface that calculates the derivative w.r.t. the nodal coordinates $ X_{pq} $ of the derivative of the shape functions $ \psi_j $ w.r.t. the global eulerian coordinates $ x_i $. I.e. this function calculates.
template<unsigned DIM>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
Calculate the derivative w.r.t. the nodal coordinates $ X_{pq} $ of the derivative of the shape functions w.r.t. the global eulerian coordinates $ x_i $, using the determinant of the jacobian mapping, its derivative w.r.t. the nodal coordinates $ X_{pq} $, the inverse jacobian and the derivatives of the shape functions w.r.t. the local coordinates. The result is returned as a tensor of rank four. Numbering: d_dpsidx_dX(p,q,j,i) = $ \frac{\partial}{\partial X_{pq}} \left( \frac{\partial \psi_j}{\partial x_i} \right) $ This function is templated by the dimension of the element.
virtual void transform_derivatives (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
Convert derivative w.r.t.local coordinates to derivatives w.r.t the coordinates used to assemble the inverse_jacobian passed in the mapping. On entry, dbasis must contain the basis function derivatives w.r.t. the local coordinates; it will contain the derivatives w.r.t. the new coordinates on exit. This is virtual so that it may be overloaded if desired for efficiency reasons.
void transform_derivatives_diagonal (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
Convert derivative w.r.t local coordinates to derivatives w.r.t the coordinates used to assemble the inverse jacobian passed in the mapping, assuming that the coordinates are aligned in the direction of the local coordinates. On entry dbasis must contain the derivatives of the basis functions w.r.t. the local coordinates; it will contain the derivatives w.r.t. the new coordinates. are converted into the new using the mapping inverse_jacobian.
virtual void transform_second_derivatives (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Convert derivatives and second derivatives w.r.t. local coordiantes to derivatives and second derivatives w.r.t. the coordinates used to assemble the jacobian, inverse jacobian and jacobian2 passed to the function. By default this function will call transform_second_derivatives_template<>(...) using the dimension of the element as the template parameter. It is virtual so that it can be overloaded by a specific element to save using a switch statement. Optionally, the element writer may wish to use the transform_second_derivatives_diagonal<>(...) function On entry dbasis and d2basis must contain the derivatives w.r.t. the local coordinates; on exit they will be the derivatives w.r.t. the transformed coordinates.
template<unsigned DIM>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Convert derivatives and second derivatives w.r.t. local coordinates to derivatives and second derivatives w.r.t. the coordinates used to asssmble the jacobian, inverse jacobian and jacobian2 passed in the mapping. This is templated by dimension because the method of calculation varies significantly with the dimension. On entry dbasis and d2basis must contain the derivatives w.r.t. the local coordinates; on exit they will be the derivatives w.r.t. the transformed coordinates.
template<unsigned DIM>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Convert derivatives and second derivatives w.r.t. local coordinates to derivatives and second derivatives w.r.t. the coordinates used to asssmble the jacobian, inverse jacobian and jacobian2 passed in the mapping. This version of the function assumes that the local coordinates are aligned with the global coordinates, i.e. the jacobians are diagonal On entry dbasis and d2basis must contain the derivatives w.r.t. the local coordinates; on exit they will be the derivatives w.r.t. the transformed coordinates.
void fill_in_jacobian_from_nodal_by_fd (DenseMatrix< double > &jacobian)
Calculate the contributions to the jacobian from the nodal degrees of freedom using finite differences. This version computes the residuals vector before calculating the jacobian terms.
virtual void update_before_nodal_fd ()
Function that is called before the finite differencing of any nodal data. This may be overloaded to update any dependent data before finite differencing takes place.
virtual void reset_after_nodal_fd ()
Function that is call after the finite differencing of the nodal data. This may be overloaded to reset any dependent variables that may have changed during the finite differencing.
virtual void update_in_nodal_fd (const unsigned &i)
Function called within the finite difference loop for nodal data after a change in the i-th nodal value.
virtual void reset_in_nodal_fd (const unsigned &i)
Function called within the finite difference loop for nodal data after the i-th nodal values is reset. The default behaviour is to call the update function.
template<> double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Zero-d specialisation of function to calculate inverse of jacobian mapping.
template<> double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
One-d specialisation of function to calculate inverse of jacobian mapping.
template<> double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Two-d specialisation of function to calculate inverse of jacobian mapping.
template<> double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Three-d specialisation of function to calculate inverse of jacobian mapping.
template<> void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
Zero-d specialisation of function to calculate the derivative of the jacobian of a mapping with respect to the nodal coordinates X_ij.
template<> void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
One-d specialisation of function to calculate the derivative of the jacobian of a mapping with respect to the nodal coordinates X_ij.
template<> void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
Two-d specialisation of function to calculate the derivative of the jacobian of a mapping with respect to the nodal coordinates X_ij.
template<> void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
Three-d specialisation of function to calculate the derivative of the jacobian of a mapping with respect to the nodal coordinates X_ij.
template<> void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
Zero-d specialisation of function to calculate the derivative w.r.t. the nodal coordinates $ X_{pq} $ of the derivative of the shape functions w.r.t. the global eulerian coordinates $ x_i $.
template<> void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
One-d specialisation of function to calculate the derivative w.r.t. the nodal coordinates $ X_{pq} $ of the derivative of the shape functions w.r.t. the global eulerian coordinates $ x_i $.
template<> void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
Two-d specialisation of function to calculate the derivative w.r.t. the nodal coordinates $ X_{pq} $ of the derivative of the shape functions w.r.t. the global eulerian coordinates $ x_i $.
template<> void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
Three-d specialisation of function to calculate the derivative w.r.t. the nodal coordinates $ X_{pq} $ of the derivative of the shape functions w.r.t. the global eulerian coordinates $ x_i $.
template<> void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Convert derivatives and second derivatives w.r.t local coordinates to derivatives w.r.t. the coordinates used to assemble the jacobian, inverse_jacobian and jacobian 2 passed. This must be specialised for each dimension, otherwise it gets very ugly Specialisation to one dimension.
template<> void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Convert derivatives and second derivatives w.r.t local coordinates to derivatives w.r.t. the coordinates used to assemble the jacobian, inverse_jacobian and jacobian 2 passed. This must be specialised for each dimension, otherwise it gets very ugly. Specialisation to two spatial dimensions.
template<> void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Convert derivatives and second derivatives w.r.t local coordinates to derivatives w.r.t. the coordinates used to assemble the jacobian, inverse_jacobian and jacobian 2 passed. This must be specialised for each dimension, otherwise it gets very ugly Specialisation to one dimension.
template<> void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Convert second derivatives w.r.t. local coordinates to second derivatives w.r.t. the coordinates passed in the tensor coordinate. Specialised to two spatial dimension.
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
Add a (pointer to an) internal data object to the element and return the index required to obtain it from the access function internal_data_pt(). The boolean indicates whether the datum should be included in the general finite-difference loop when calculating the jacobian. The default value is true, i.e. the data will be included in the finite differencing.
bool internal_data_fd (const unsigned &i) const
Return the status of the boolean flag indicating whether the internal data is included in the finite difference loop.
void exclude_internal_data_fd (const unsigned &i)
Set the boolean flag to exclude the internal datum from the finite difference loop when computing the jacobian matrix.
void include_internal_data_fd (const unsigned &i)
Set the boolean flag to include the internal datum in the finite difference loop when computing the jacobian matrix.
void clear_global_eqn_numbers ()
Clear the storage for the global equation numbers and pointers to dofs (if stored)
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
Add the contents of the queue global_eqn_numbers to the local storage for the local-to-global translation scheme. It is essential that the entries in the queue are added IN ORDER i.e. from the front.
virtual void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
Assign the local equation numbers for the internal and external Data This must be called after the global equation numbers have all been assigned. It is virtual so that it can be overloaded by ElementWithExternalElements so that any external data from the external elements in included in the numbering scheme. If the boolean argument is true then pointers to the dofs will be stored in Dof_pt.
virtual void assign_additional_local_eqn_numbers ()
Setup any additional look-up schemes for local equation numbers. Examples of use include using local storage to refer to explicit degrees of freedom. The additional memory cost of such storage may or may not be offset by fast local access.
int internal_local_eqn (const unsigned &i, const unsigned &j) const
Return the local equation number corresponding to the j-th value stored at the i-th internal data.
int external_local_eqn (const unsigned &i, const unsigned &j)
Return the local equation number corresponding to the j-th value stored at the i-th external data.
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
Calculate the contributions to the jacobian from the internal degrees of freedom using finite differences. This version of the function assumes that the residuals vector has already been calculated. If the boolean argument is true, the finite differencing will be performed for all internal data, irrespective of the information in Data_fd. The default value (false) uses the information in Data_fd to selectively difference only certain data.
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
Calculate the contributions to the jacobian from the internal degrees of freedom using finite differences. This version computes the residuals vector before calculating the jacobian terms. If the boolean argument is true, the finite differencing will be performed for all internal data, irrespective of the information in Data_fd. The default value (false) uses the information in Data_fd to selectively difference only certain data.
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
Calculate the contributions to the jacobian from the external degrees of freedom using finite differences. This version of the function assumes that the residuals vector has already been calculated. If the boolean argument is true, the finite differencing will be performed for all external data, irrespective of the information in Data_fd. The default value (false) uses the information in Data_fd to selectively difference only certain data.
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
Calculate the contributions to the jacobian from the external degrees of freedom using finite differences. This version computes the residuals vector before calculating the jacobian terms. If the boolean argument is true, the finite differencing will be performed for all internal data, irrespective of the information in Data_fd. The default value (false) uses the information in Data_fd to selectively difference only certain data.
virtual void update_before_internal_fd ()
Function that is called before the finite differencing of any internal data. This may be overloaded to update any dependent data before finite differencing takes place.
virtual void reset_after_internal_fd ()
Function that is call after the finite differencing of the internal data. This may be overloaded to reset any dependent variables that may have changed during the finite differencing.
virtual void update_in_internal_fd (const unsigned &i)
Function called within the finite difference loop for internal data after a change in any values in the i-th internal data object.
virtual void reset_in_internal_fd (const unsigned &i)
Function called within the finite difference loop for internal data after the values in the i-th external data object are reset. The default behaviour is to call the update function.
virtual void update_before_external_fd ()
Function that is called before the finite differencing of any external data. This may be overloaded to update any dependent data before finite differencing takes place.
virtual void reset_after_external_fd ()
Function that is call after the finite differencing of the external data. This may be overloaded to reset any dependent variables that may have changed during the finite differencing.
virtual void update_in_external_fd (const unsigned &i)
Function called within the finite difference loop for external data after a change in any values in the i-th external data object.
virtual void reset_in_external_fd (const unsigned &i)
Function called within the finite difference loop for external data after the values in the i-th external data object are reset. The default behaviour is to call the update function.
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
Add the elemental contribution to the mass matrix matrix. and the residuals vector. Note that this function should NOT initialise the residuals vector or the mass matrix. It must be called after the residuals vector and jacobian matrix have been initialised to zero. The default is deliberately broken.
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned > > const &history_index, Vector< double > &inner_product)
Fill in the contribution to the inner products between given pairs of history values.
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double > > &inner_product_vector)
Fill in the contributions to the vectors that when taken as dot product with other history values give the inner product over the element.
Protected Member Functions inherited from oomph::RefineableSpaceTimeNavierStokesEquations< DIM >
void fill_in_generic_residual_contribution_nst (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, const unsigned &compute_jacobian_flag)
Add the elements contribution to elemental residual vector and/or Jacobian matrix. compute_jacobian_flag=0: compute residual vector only compute_jacobian_flag=1: compute both.
void fill_in_generic_pressure_advection_diffusion_contribution_nst (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &compute_jacobian_flag)
Compute the residuals for the associated pressure advection diffusion problem. Used by the Fp preconditioner. flag=1(or 0): do (or don't) compute the Jacobian as well.
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
Compute derivatives of elemental residual vector with respect to nodal coordinates. Overwrites default implementation in FiniteElement base class. dresidual_dnodal_coordinates(l,i,j) = d res(l) / dX_{ij}.
void fill_in_generic_residual_contribution_nst (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, const unsigned &compute_jacobian_flag)
Add the elements contribution to elemental residual vector and/or Jacobian matrix. compute_jacobian_flag=0: compute residual vector only compute_jacobian_flag=1: compute both.
void fill_in_generic_pressure_advection_diffusion_contribution_nst (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &compute_jacobian_flag)
Compute the residuals for the associated pressure advection diffusion problem. Used by the Fp preconditioner. flag=1(or 0): do (or don't) compute the Jacobian as well.
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
Compute derivatives of elemental residual vector with respect to nodal coordinates. Overwrites default implementation in FiniteElement base class. dresidual_dnodal_coordinates(l,i,j) = d res(l) / dX_{ij}.
void fill_in_generic_residual_contribution_nst (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, const unsigned &compute_jacobian_flag)
Add the elements contribution to elemental residual vector and/or Jacobian matrix. compute_jacobian_flag=0: compute residual vector only compute_jacobian_flag=1: compute both.
void fill_in_generic_pressure_advection_diffusion_contribution_nst (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &compute_jacobian_flag)
Compute the residuals for the associated pressure advection diffusion problem. Used by the Fp preconditioner. flag=1(or 0): do (or don't) compute the Jacobian as well.
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
Compute derivatives of elemental residual vector with respect to nodal coordinates. Overwrites default implementation in FiniteElement base class. dresidual_dnodal_coordinates(l,i,j) = d res(l) / dX_{ij}.
Protected Member Functions inherited from oomph::RefineableElement
void assemble_local_to_eulerian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
Assemble the jacobian matrix for the mapping from local to Eulerian coordinates, given the derivatives of the shape function w.r.t the local coordinates. Overload the standard version to use the hanging information for the Eulerian coordinates.
void assemble_local_to_eulerian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
Assemble the the "jacobian" matrix of second derivatives of the mapping from local to Eulerian coordinates, given the second derivatives of the shape functions w.r.t. local coordinates. Overload the standard version to use the hanging information for the Eulerian coordinates.
void assemble_eulerian_base_vectors (const DShape &dpsids, DenseMatrix< double > &interpolated_G) const
Assemble the covariant Eulerian base vectors, assuming that the derivatives of the shape functions with respect to the local coordinates have already been constructed. Overload the standard version to account for hanging nodes.
double local_to_eulerian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Calculate the mapping from local to Eulerian coordinates given the derivatives of the shape functions w.r.t the local coordinates. assuming that the coordinates are aligned in the direction of the local coordinates, i.e. there are no cross terms and the jacobian is diagonal. This funciton returns the determinant of the jacobian, the jacobian and the inverse jacobian. Overload the standard version to take hanging info into account.
void assign_hanging_local_eqn_numbers (const bool &store_local_dof_pt)
Assign the local equation numbers for hanging node variables.
virtual void fill_in_jacobian_from_nodal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Calculate the contributions to the jacobian from the nodal degrees of freedom using finite differences. This version is overloaded to take hanging node information into account.
Static Protected Member Functions inherited from oomph::RefineableElement
static void check_value_id (const int &n_continuously_interpolated_values, const int &value_id)
Static helper function that is used to check that the value_id is in range.
Protected Attributes inherited from oomph::SpaceTimeNavierStokesEquations< DIM >
double * Viscosity_Ratio_pt
Pointer to the viscosity ratio (relative to the viscosity used in the definition of the Reynolds number)
double * Density_Ratio_pt
Pointer to the density ratio (relative to the density used in the definition of the Reynolds number)
double * Re_pt
Pointer to global Reynolds number.
double * St_pt
Pointer to global Reynolds number x Strouhal number (=Womersley)
bool Strouhal_is_stored_as_external_data
Boolean to indicate whether or not the Strouhal value is stored as external data (if it's also an unknown of the problem)
double * ReInvFr_pt
Pointer to global Reynolds number x inverse Froude number (= Bond number / Capillary number)
Vector< double > * G_pt
Pointer to global gravity Vector.
NavierStokesBodyForceFctPt Body_force_fct_pt
Pointer to body force function.
NavierStokesSourceFctPt Source_fct_pt
Pointer to volumetric source function.
NavierStokesPressureAdvDiffSourceFctPt Press_adv_diff_source_fct_pt
Pointer to source function pressure advection diffusion equation (only to be used during validation)
bool ALE_is_disabled
Boolean flag to indicate if ALE formulation is disabled when time-derivatives are computed. Only set to true if you're sure that the mesh is stationary.
Vector< FpPressureAdvDiffRobinBCSpaceTimeElementBase * > Pressure_advection_diffusion_robin_element_pt
Storage for FaceElements that apply Robin BC for pressure adv diff equation used in Fp preconditioner.
int Pinned_fp_pressure_eqn
Global eqn number of pressure dof that's pinned in pressure advection diffusion problem (defaults to -1)
double * ReSt_pt
Pointer to global Reynolds number x Strouhal number (= Womersley)
bool ReynoldsStrouhal_is_stored_as_external_data
Boolean to indicate whether or not the Strouhal value is stored as external data (if it's also an unknown of the problem)
Protected Attributes inherited from oomph::FiniteElement
MacroElement * Macro_elem_pt
Pointer to the element's macro element (NULL by default)
Protected Attributes inherited from oomph::GeneralisedElement
int Non_halo_proc_ID
Non-halo processor ID for Data; -1 if it's not a halo.
bool Must_be_kept_as_halo
Does this element need to be kept as a halo element during a distribute?
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Timestepper (used to handle access to geometry at previous timesteps)
Protected Attributes inherited from oomph::RefineableElement
Tree * Tree_pt
A pointer to a general tree object.
unsigned Refine_level
Refinement level.
bool To_be_refined
Flag for refinement.
bool Refinement_is_enabled
Flag to indicate suppression of any refinement.
bool Sons_to_be_unrefined
Flag for unrefinement.
long Number
Global element number -- for plotting/validation purposes.
Static Protected Attributes inherited from oomph::QTaylorHoodSpaceTimeElement< DIM >
static const unsigned Pconv []
Static array of ints to hold conversion from pressure node numbers to actual node numbers.
Static Protected Attributes inherited from oomph::FiniteElement
static const unsigned Default_Initial_Nvalue = 0
Default return value for required_nvalue(n) which gives the number of "data" values required by the element at node n; for example, solving a Poisson equation would required only one "data" value at each node. The defaults is set to zero, because a general element is problem-less.
static const double Node_location_tolerance = 1.0e-14
Default value for the tolerance to be used when locating nodes via local coordinates.
static const unsigned N2deriv [] = {0, 1, 3, 6}
Static array that holds the number of second derivatives as a function of the dimension of the element.
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
Empty dense matrix used as a dummy argument to combined residual and jacobian functions in the case when only the residuals are being assembled.
static std::deque< double * > Dof_pt_deque
Static storage for deque used to add_global_equation_numbers when pointers to the dofs in each element are not required.
Static Protected Attributes inherited from oomph::RefineableElement
static double Max_integrity_tolerance = 1.0e-8
Max. allowed discrepancy in element integrity check.
Detailed Description
template<unsigned DIM>
class oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >
Refineable version of Taylor Hood elements. These classes can be written in total generality.
Definition at line 758 of file refineable_discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
Constructor & Destructor Documentation
RefineableQTaylorHoodSpaceTimeElement() [1/3]
template<unsigned DIM>
oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::RefineableQTaylorHoodSpaceTimeElement () [inline]
Constructor.
Definition at line 765 of file refineable_discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
RefineableQTaylorHoodSpaceTimeElement() [2/3]
template<unsigned DIM>
oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::RefineableQTaylorHoodSpaceTimeElement () [inline]
Constructor.
Definition at line 765 of file refineable_discontinuous_galerkin_spacetime_navier_stokes_elements.h.
RefineableQTaylorHoodSpaceTimeElement() [3/3]
template<unsigned DIM>
oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::RefineableQTaylorHoodSpaceTimeElement () [inline]
Constructor.
Definition at line 765 of file refineable_spacetime_navier_stokes_elements.h.
Member Function Documentation
build_fp_press_adv_diff_robin_bc_element() [1/3]
template<unsigned DIM>
void oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::build_fp_press_adv_diff_robin_bc_element (const unsigned & face_index) [inline], [virtual]
Build FaceElements that apply the Robin boundary condition to the pressure advection diffusion problem required by Fp preconditioner.
Reimplemented from oomph::QTaylorHoodSpaceTimeElement< DIM >.
Definition at line 1073 of file refineable_discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References oomph::SpaceTimeNavierStokesEquations< DIM >::Pressure_advection_diffusion_robin_element_pt.
build_fp_press_adv_diff_robin_bc_element() [2/3]
template<unsigned DIM>
void oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::build_fp_press_adv_diff_robin_bc_element (const unsigned & face_index) [inline], [virtual]
Build FaceElements that apply the Robin boundary condition to the pressure advection diffusion problem required by Fp preconditioner.
Reimplemented from oomph::QTaylorHoodSpaceTimeElement< DIM >.
Definition at line 1073 of file refineable_discontinuous_galerkin_spacetime_navier_stokes_elements.h.
References oomph::SpaceTimeNavierStokesEquations< DIM >::Pressure_advection_diffusion_robin_element_pt.
build_fp_press_adv_diff_robin_bc_element() [3/3]
template<unsigned DIM>
void oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::build_fp_press_adv_diff_robin_bc_element (const unsigned & face_index) [inline], [virtual]
Build FaceElements that apply the Robin boundary condition to the pressure advection diffusion problem required by Fp preconditioner.
Reimplemented from oomph::QTaylorHoodSpaceTimeElement< DIM >.
Definition at line 1073 of file refineable_spacetime_navier_stokes_elements.h.
References oomph::SpaceTimeNavierStokesEquations< DIM >::Pressure_advection_diffusion_robin_element_pt.
further_setup_hanging_nodes() [1/3]
template<unsigned DIM>
void oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::further_setup_hanging_nodes () [inline], [virtual]
Perform additional hanging node procedures for variables that are not interpolated by all nodes. The pressures are stored at the p_nodal_index_nst-th location in each node.
Reimplemented from oomph::RefineableElement.
Definition at line 877 of file refineable_discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References oomph::QTaylorHoodSpaceTimeElement< DIM >::p_nodal_index_nst().
further_setup_hanging_nodes() [2/3]
template<unsigned DIM>
void oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::further_setup_hanging_nodes () [inline], [virtual]
Perform additional hanging node procedures for variables that are not interpolated by all nodes. The pressures are stored at the p_nodal_index_nst-th location in each node.
Reimplemented from oomph::RefineableElement.
Definition at line 877 of file refineable_discontinuous_galerkin_spacetime_navier_stokes_elements.h.
References oomph::QTaylorHoodSpaceTimeElement< DIM >::p_nodal_index_nst().
further_setup_hanging_nodes() [3/3]
template<unsigned DIM>
void oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::further_setup_hanging_nodes () [inline], [virtual]
Perform additional hanging node procedures for variables that are not interpolated by all nodes. The pressures are stored at the p_nodal_index_nst-th location in each node.
Reimplemented from oomph::RefineableElement.
Definition at line 877 of file refineable_spacetime_navier_stokes_elements.h.
References oomph::QTaylorHoodSpaceTimeElement< DIM >::p_nodal_index_nst().
get_interpolated_values() [1/6]
template<unsigned DIM>
void oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::get_interpolated_values (const unsigned & t, const Vector< double > & s, Vector< double > & values) [inline], [virtual]
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Implements oomph::RefineableElement.
Definition at line 847 of file refineable_discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::get_interpolated_values(), s, and t.
get_interpolated_values() [2/6]
template<unsigned DIM>
void oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::get_interpolated_values (const unsigned & t, const Vector< double > & s, Vector< double > & values) [inline], [virtual]
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Implements oomph::RefineableElement.
Definition at line 847 of file refineable_discontinuous_galerkin_spacetime_navier_stokes_elements.h.
References oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::get_interpolated_values(), s, and t.
get_interpolated_values() [3/6]
template<unsigned DIM>
void oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::get_interpolated_values (const unsigned & t, const Vector< double > & s, Vector< double > & values) [inline], [virtual]
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Implements oomph::RefineableElement.
Definition at line 847 of file refineable_spacetime_navier_stokes_elements.h.
References oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::get_interpolated_values(), s, and t.
get_interpolated_values() [4/6]
template<unsigned DIM>
void oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::get_interpolated_values (const Vector< double > & s, Vector< double > & values) [inline], [virtual]
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Reimplemented from oomph::RefineableElement.
Definition at line 825 of file refineable_discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References i, oomph::SpaceTimeNavierStokesEquations< DIM >::interpolated_p_nst(), and oomph::SpaceTimeNavierStokesEquations< DIM >::interpolated_u_nst().
Referenced by oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::get_interpolated_values().
get_interpolated_values() [5/6]
template<unsigned DIM>
void oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::get_interpolated_values (const Vector< double > & s, Vector< double > & values) [inline], [virtual]
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Reimplemented from oomph::RefineableElement.
Definition at line 825 of file refineable_discontinuous_galerkin_spacetime_navier_stokes_elements.h.
References i, oomph::SpaceTimeNavierStokesEquations< DIM >::interpolated_p_nst(), and oomph::SpaceTimeNavierStokesEquations< DIM >::interpolated_u_nst().
get_interpolated_values() [6/6]
template<unsigned DIM>
void oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::get_interpolated_values (const Vector< double > & s, Vector< double > & values) [inline], [virtual]
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Reimplemented from oomph::RefineableElement.
Definition at line 825 of file refineable_spacetime_navier_stokes_elements.h.
References i, oomph::SpaceTimeNavierStokesEquations< DIM >::interpolated_p_nst(), and oomph::SpaceTimeNavierStokesEquations< DIM >::interpolated_u_nst().
get_interpolating_node_at_local_coordinate() [1/3]
template<unsigned DIM>
Node * oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::get_interpolating_node_at_local_coordinate (const Vector< double > & s, const int & value_id) [inline], [virtual]
The velocity nodes are the same as the geometric nodes. The pressure nodes must be calculated by using the same methods as the geometric nodes, but by recalling that there are only two pressure nodes per edge.
Reimplemented from oomph::RefineableElement.
Definition at line 939 of file refineable_discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References oomph::FiniteElement::get_node_at_local_coordinate(), i, oomph::FiniteElement::nnode_1d(), oomph::FiniteElement::Node_location_tolerance, oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::pressure_node_pt(), and s.
get_interpolating_node_at_local_coordinate() [2/3]
template<unsigned DIM>
Node * oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::get_interpolating_node_at_local_coordinate (const Vector< double > & s, const int & value_id) [inline], [virtual]
The velocity nodes are the same as the geometric nodes. The pressure nodes must be calculated by using the same methods as the geometric nodes, but by recalling that there are only two pressure nodes per edge.
Reimplemented from oomph::RefineableElement.
Definition at line 939 of file refineable_discontinuous_galerkin_spacetime_navier_stokes_elements.h.
References oomph::FiniteElement::get_node_at_local_coordinate(), i, oomph::FiniteElement::nnode_1d(), oomph::FiniteElement::Node_location_tolerance, oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::pressure_node_pt(), and s.
get_interpolating_node_at_local_coordinate() [3/3]
template<unsigned DIM>
Node * oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::get_interpolating_node_at_local_coordinate (const Vector< double > & s, const int & value_id) [inline], [virtual]
The velocity nodes are the same as the geometric nodes. The pressure nodes must be calculated by using the same methods as the geometric nodes, but by recalling that there are only two pressure nodes per edge.
Reimplemented from oomph::RefineableElement.
Definition at line 939 of file refineable_spacetime_navier_stokes_elements.h.
References oomph::FiniteElement::get_node_at_local_coordinate(), i, oomph::FiniteElement::nnode_1d(), oomph::FiniteElement::Node_location_tolerance, oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::pressure_node_pt(), and s.
identify_load_data() [1/3]
template<unsigned DIM>
void oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::identify_load_data (std::set< std::pair< Data *, unsigned > > & paired_load_data) [inline], [virtual]
Add to the set paired_load_data pairs containing.
the pointer to a Data object and
the index of the value in that Data object
for all values (pressures, velocities) that affect the load computed in the get_load(...) function. (Overloads non-refineable version and takes hanging nodes into account)
Reimplemented from oomph::QTaylorHoodSpaceTimeElement< DIM >.
Definition at line 1090 of file refineable_discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References i, oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::QTaylorHoodSpaceTimeElement< DIM >::npres_nst(), oomph::QTaylorHoodSpaceTimeElement< DIM >::p_nodal_index_nst(), oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::pressure_node_pt(), and oomph::SpaceTimeNavierStokesEquations< DIM >::u_index_nst().
identify_load_data() [2/3]
template<unsigned DIM>
void oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::identify_load_data (std::set< std::pair< Data *, unsigned > > & paired_load_data) [inline], [virtual]
Add to the set paired_load_data pairs containing.
the pointer to a Data object and
the index of the value in that Data object
for all values (pressures, velocities) that affect the load computed in the get_load(...) function. (Overloads non-refineable version and takes hanging nodes into account)
Reimplemented from oomph::QTaylorHoodSpaceTimeElement< DIM >.
Definition at line 1090 of file refineable_discontinuous_galerkin_spacetime_navier_stokes_elements.h.
References i, oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::QTaylorHoodSpaceTimeElement< DIM >::npres_nst(), oomph::QTaylorHoodSpaceTimeElement< DIM >::p_nodal_index_nst(), oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::pressure_node_pt(), and oomph::SpaceTimeNavierStokesEquations< DIM >::u_index_nst().
identify_load_data() [3/3]
template<unsigned DIM>
void oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::identify_load_data (std::set< std::pair< Data *, unsigned > > & paired_load_data) [inline], [virtual]
Add to the set paired_load_data pairs containing.
the pointer to a Data object and
the index of the value in that Data object
for all values (pressures, velocities) that affect the load computed in the get_load(...) function. (Overloads non-refineable version and takes hanging nodes into account)
Reimplemented from oomph::QTaylorHoodSpaceTimeElement< DIM >.
Definition at line 1090 of file refineable_spacetime_navier_stokes_elements.h.
References i, oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::QTaylorHoodSpaceTimeElement< DIM >::npres_nst(), oomph::QTaylorHoodSpaceTimeElement< DIM >::p_nodal_index_nst(), oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::pressure_node_pt(), and oomph::SpaceTimeNavierStokesEquations< DIM >::u_index_nst().
interpolating_basis() [1/3]
template<unsigned DIM>
void oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::interpolating_basis (const Vector< double > & s, Shape & psi, const int & value_id) const [inline], [virtual]
The basis interpolating the pressure is given by pshape(). / The basis interpolating the velocity is shape().
Reimplemented from oomph::RefineableElement.
Definition at line 1051 of file refineable_discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References oomph::QTaylorHoodSpaceTimeElement< DIM >::pshape_nst(), and oomph::FiniteElement::shape().
interpolating_basis() [2/3]
template<unsigned DIM>
void oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::interpolating_basis (const Vector< double > & s, Shape & psi, const int & value_id) const [inline], [virtual]
The basis interpolating the pressure is given by pshape(). / The basis interpolating the velocity is shape().
Reimplemented from oomph::RefineableElement.
Definition at line 1051 of file refineable_discontinuous_galerkin_spacetime_navier_stokes_elements.h.
References oomph::QTaylorHoodSpaceTimeElement< DIM >::pshape_nst(), and oomph::FiniteElement::shape().
interpolating_basis() [3/3]
template<unsigned DIM>
void oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::interpolating_basis (const Vector< double > & s, Shape & psi, const int & value_id) const [inline], [virtual]
The basis interpolating the pressure is given by pshape(). / The basis interpolating the velocity is shape().
Reimplemented from oomph::RefineableElement.
Definition at line 1051 of file refineable_spacetime_navier_stokes_elements.h.
References oomph::QTaylorHoodSpaceTimeElement< DIM >::pshape_nst(), and oomph::FiniteElement::shape().
interpolating_node_pt() [1/3]
template<unsigned DIM>
Node * oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::interpolating_node_pt (const unsigned & n, const int & value_id) [inline], [virtual]
The velocities are isoparametric and so the "nodes" interpolating the velocities are the geometric nodes. The pressure "nodes" are a subset of the nodes, so when value_id==DIM, the n-th pressure node is returned.
Reimplemented from oomph::RefineableElement.
Definition at line 896 of file refineable_discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References oomph::FiniteElement::node_pt(), and oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::pressure_node_pt().
interpolating_node_pt() [2/3]
template<unsigned DIM>
Node * oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::interpolating_node_pt (const unsigned & n, const int & value_id) [inline], [virtual]
The velocities are isoparametric and so the "nodes" interpolating the velocities are the geometric nodes. The pressure "nodes" are a subset of the nodes, so when value_id==DIM, the n-th pressure node is returned.
Reimplemented from oomph::RefineableElement.
Definition at line 896 of file refineable_discontinuous_galerkin_spacetime_navier_stokes_elements.h.
References oomph::FiniteElement::node_pt(), and oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::pressure_node_pt().
interpolating_node_pt() [3/3]
template<unsigned DIM>
Node * oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::interpolating_node_pt (const unsigned & n, const int & value_id) [inline], [virtual]
The velocities are isoparametric and so the "nodes" interpolating the velocities are the geometric nodes. The pressure "nodes" are a subset of the nodes, so when value_id==DIM, the n-th pressure node is returned.
Reimplemented from oomph::RefineableElement.
Definition at line 896 of file refineable_spacetime_navier_stokes_elements.h.
References oomph::FiniteElement::node_pt(), and oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::pressure_node_pt().
local_one_d_fraction_of_interpolating_node() [1/3]
template<unsigned DIM>
double oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::local_one_d_fraction_of_interpolating_node (const unsigned & n_1d, const unsigned & i, const int & value_id) [inline], [virtual]
The pressure nodes are the corner nodes, so when n_value==DIM, the fraction is the same as the 1D node number, 0 or 1.
Reimplemented from oomph::RefineableElement.
Definition at line 916 of file refineable_discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References i, and oomph::FiniteElement::local_one_d_fraction_of_node().
local_one_d_fraction_of_interpolating_node() [2/3]
template<unsigned DIM>
double oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::local_one_d_fraction_of_interpolating_node (const unsigned & n_1d, const unsigned & i, const int & value_id) [inline], [virtual]
The pressure nodes are the corner nodes, so when n_value==DIM, the fraction is the same as the 1D node number, 0 or 1.
Reimplemented from oomph::RefineableElement.
Definition at line 916 of file refineable_discontinuous_galerkin_spacetime_navier_stokes_elements.h.
References i, and oomph::FiniteElement::local_one_d_fraction_of_node().
local_one_d_fraction_of_interpolating_node() [3/3]
template<unsigned DIM>
double oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::local_one_d_fraction_of_interpolating_node (const unsigned & n_1d, const unsigned & i, const int & value_id) [inline], [virtual]
The pressure nodes are the corner nodes, so when n_value==DIM, the fraction is the same as the 1D node number, 0 or 1.
Reimplemented from oomph::RefineableElement.
Definition at line 916 of file refineable_spacetime_navier_stokes_elements.h.
References i, and oomph::FiniteElement::local_one_d_fraction_of_node().
ncont_interpolated_values() [1/3]
template<unsigned DIM>
unsigned oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::ncont_interpolated_values () const [inline], [virtual]
Number of continuously interpolated values.
Implements oomph::RefineableElement.
Definition at line 785 of file refineable_discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
ncont_interpolated_values() [2/3]
template<unsigned DIM>
unsigned oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::ncont_interpolated_values () const [inline], [virtual]
Number of continuously interpolated values.
Implements oomph::RefineableElement.
Definition at line 785 of file refineable_discontinuous_galerkin_spacetime_navier_stokes_elements.h.
ncont_interpolated_values() [3/3]
template<unsigned DIM>
unsigned oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::ncont_interpolated_values () const [inline], [virtual]
Number of continuously interpolated values.
Implements oomph::RefineableElement.
Definition at line 785 of file refineable_spacetime_navier_stokes_elements.h.
ninterpolating_node() [1/3]
template<unsigned DIM>
unsigned oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::ninterpolating_node (const int & value_id) [inline], [virtual]
The number of pressure nodes is 2^DIM. The number of velocity nodes is the same as the number of geometric nodes.
Reimplemented from oomph::RefineableElement.
Definition at line 1032 of file refineable_discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References oomph::FiniteElement::nnode().
ninterpolating_node() [2/3]
template<unsigned DIM>
unsigned oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::ninterpolating_node (const int & value_id) [inline], [virtual]
The number of pressure nodes is 2^DIM. The number of velocity nodes is the same as the number of geometric nodes.
Reimplemented from oomph::RefineableElement.
Definition at line 1032 of file refineable_discontinuous_galerkin_spacetime_navier_stokes_elements.h.
References oomph::FiniteElement::nnode().
ninterpolating_node() [3/3]
template<unsigned DIM>
unsigned oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::ninterpolating_node (const int & value_id) [inline], [virtual]
The number of pressure nodes is 2^DIM. The number of velocity nodes is the same as the number of geometric nodes.
Reimplemented from oomph::RefineableElement.
Definition at line 1032 of file refineable_spacetime_navier_stokes_elements.h.
References oomph::FiniteElement::nnode().
ninterpolating_node_1d() [1/3]
template<unsigned DIM>
unsigned oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::ninterpolating_node_1d (const int & value_id) [inline], [virtual]
The number of 1D pressure nodes is 2, the number of 1D velocity nodes is the same as the number of 1D geometric nodes.
Reimplemented from oomph::RefineableElement.
Definition at line 1013 of file refineable_discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References oomph::FiniteElement::nnode_1d().
ninterpolating_node_1d() [2/3]
template<unsigned DIM>
unsigned oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::ninterpolating_node_1d (const int & value_id) [inline], [virtual]
The number of 1D pressure nodes is 2, the number of 1D velocity nodes is the same as the number of 1D geometric nodes.
Reimplemented from oomph::RefineableElement.
Definition at line 1013 of file refineable_discontinuous_galerkin_spacetime_navier_stokes_elements.h.
References oomph::FiniteElement::nnode_1d().
ninterpolating_node_1d() [3/3]
template<unsigned DIM>
unsigned oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::ninterpolating_node_1d (const int & value_id) [inline], [virtual]
The number of 1D pressure nodes is 2, the number of 1D velocity nodes is the same as the number of 1D geometric nodes.
Reimplemented from oomph::RefineableElement.
Definition at line 1013 of file refineable_spacetime_navier_stokes_elements.h.
References oomph::FiniteElement::nnode_1d().
nrecovery_order() [1/3]
template<unsigned DIM>
unsigned oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::nrecovery_order () [inline], [virtual]
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 798 of file refineable_discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
nrecovery_order() [2/3]
template<unsigned DIM>
unsigned oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::nrecovery_order () [inline], [virtual]
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 798 of file refineable_discontinuous_galerkin_spacetime_navier_stokes_elements.h.
nrecovery_order() [3/3]
template<unsigned DIM>
unsigned oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::nrecovery_order () [inline], [virtual]
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 798 of file refineable_spacetime_navier_stokes_elements.h.
nvertex_node() [1/3]
template<unsigned DIM>
unsigned oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::nvertex_node () const [inline], [virtual]
Number of vertex nodes in the element.
Reimplemented from oomph::FiniteElement.
Definition at line 806 of file refineable_discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References oomph::FiniteElement::nvertex_node().
nvertex_node() [2/3]
template<unsigned DIM>
unsigned oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::nvertex_node () const [inline], [virtual]
Number of vertex nodes in the element.
Reimplemented from oomph::FiniteElement.
Definition at line 806 of file refineable_discontinuous_galerkin_spacetime_navier_stokes_elements.h.
References oomph::FiniteElement::nvertex_node().
nvertex_node() [3/3]
template<unsigned DIM>
unsigned oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::nvertex_node () const [inline], [virtual]
Number of vertex nodes in the element.
Reimplemented from oomph::FiniteElement.
Definition at line 806 of file refineable_spacetime_navier_stokes_elements.h.
References oomph::FiniteElement::nvertex_node().
pin_elemental_redundant_nodal_pressure_dofs() [1/3]
template<unsigned DIM>
void oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::pin_elemental_redundant_nodal_pressure_dofs () [inline], [private], [virtual]
Pin all nodal pressure dofs that are not required.
Reimplemented from oomph::RefineableSpaceTimeNavierStokesEquations< DIM >.
Definition at line 1209 of file refineable_discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::QTaylorHoodSpaceTimeElement< DIM >::npres_nst(), oomph::QTaylorHoodSpaceTimeElement< DIM >::p_nodal_index_nst(), oomph::Data::pin(), and oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::pressure_node_pt().
pin_elemental_redundant_nodal_pressure_dofs() [2/3]
template<unsigned DIM>
void oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::pin_elemental_redundant_nodal_pressure_dofs () [inline], [private], [virtual]
Pin all nodal pressure dofs that are not required.
Reimplemented from oomph::RefineableSpaceTimeNavierStokesEquations< DIM >.
Definition at line 1209 of file refineable_discontinuous_galerkin_spacetime_navier_stokes_elements.h.
References oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::QTaylorHoodSpaceTimeElement< DIM >::npres_nst(), oomph::QTaylorHoodSpaceTimeElement< DIM >::p_nodal_index_nst(), oomph::Data::pin(), and oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::pressure_node_pt().
pin_elemental_redundant_nodal_pressure_dofs() [3/3]
template<unsigned DIM>
void oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::pin_elemental_redundant_nodal_pressure_dofs () [inline], [private], [virtual]
Pin all nodal pressure dofs that are not required.
Reimplemented from oomph::RefineableSpaceTimeNavierStokesEquations< DIM >.
Definition at line 1209 of file refineable_spacetime_navier_stokes_elements.h.
References oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::QTaylorHoodSpaceTimeElement< DIM >::npres_nst(), oomph::QTaylorHoodSpaceTimeElement< DIM >::p_nodal_index_nst(), oomph::Data::pin(), and oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::pressure_node_pt().
pressure_node_pt() [1/3]
template<unsigned DIM>
Node * oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::pressure_node_pt (const unsigned & n_p) [inline], [virtual]
Pointer to n_p-th pressure node.
Reimplemented from oomph::RefineableSpaceTimeNavierStokesEquations< DIM >.
Definition at line 885 of file refineable_discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References oomph::FiniteElement::node_pt(), and oomph::QTaylorHoodSpaceTimeElement< DIM >::Pconv.
Referenced by oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::get_interpolating_node_at_local_coordinate(), oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::identify_load_data(), oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::interpolating_node_pt(), and oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::pin_elemental_redundant_nodal_pressure_dofs().
pressure_node_pt() [2/3]
template<unsigned DIM>
Node * oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::pressure_node_pt (const unsigned & n_p) [inline], [virtual]
Pointer to n_p-th pressure node.
Reimplemented from oomph::RefineableSpaceTimeNavierStokesEquations< DIM >.
Definition at line 885 of file refineable_discontinuous_galerkin_spacetime_navier_stokes_elements.h.
References oomph::FiniteElement::node_pt(), and oomph::QTaylorHoodSpaceTimeElement< DIM >::Pconv.
pressure_node_pt() [3/3]
template<unsigned DIM>
Node * oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::pressure_node_pt (const unsigned & n_p) [inline], [virtual]
Pointer to n_p-th pressure node.
Reimplemented from oomph::RefineableSpaceTimeNavierStokesEquations< DIM >.
Definition at line 885 of file refineable_spacetime_navier_stokes_elements.h.
References oomph::FiniteElement::node_pt(), and oomph::QTaylorHoodSpaceTimeElement< DIM >::Pconv.
rebuild_from_sons() [1/3]
template<unsigned DIM>
void oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::rebuild_from_sons (Mesh *& mesh_pt) [inline], [virtual]
Rebuild from sons: empty.
Implements oomph::RefineableElement.
Definition at line 793 of file refineable_discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
rebuild_from_sons() [2/3]
template<unsigned DIM>
void oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::rebuild_from_sons (Mesh *& mesh_pt) [inline], [virtual]
Rebuild from sons: empty.
Implements oomph::RefineableElement.
Definition at line 793 of file refineable_discontinuous_galerkin_spacetime_navier_stokes_elements.h.
rebuild_from_sons() [3/3]
template<unsigned DIM>
void oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::rebuild_from_sons (Mesh *& mesh_pt) [inline], [virtual]
Rebuild from sons: empty.
Implements oomph::RefineableElement.
Definition at line 793 of file refineable_spacetime_navier_stokes_elements.h.
required_nvalue() [1/3]
template<unsigned DIM>
unsigned oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::required_nvalue (const unsigned & n) const [inline], [virtual]
Number of values required at local node n. In order to simplify matters, we allocate storage for pressure variables at all the nodes and then pin those that are not used.
Reimplemented from oomph::QTaylorHoodSpaceTimeElement< DIM >.
Definition at line 777 of file refineable_discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
required_nvalue() [2/3]
template<unsigned DIM>
unsigned oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::required_nvalue (const unsigned & n) const [inline], [virtual]
Number of values required at local node n. In order to simplify matters, we allocate storage for pressure variables at all the nodes and then pin those that are not used.
Reimplemented from oomph::QTaylorHoodSpaceTimeElement< DIM >.
Definition at line 777 of file refineable_discontinuous_galerkin_spacetime_navier_stokes_elements.h.
required_nvalue() [3/3]
template<unsigned DIM>
unsigned oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::required_nvalue (const unsigned & n) const [inline], [virtual]
Number of values required at local node n. In order to simplify matters, we allocate storage for pressure variables at all the nodes and then pin those that are not used.
Reimplemented from oomph::QTaylorHoodSpaceTimeElement< DIM >.
Definition at line 777 of file refineable_spacetime_navier_stokes_elements.h.
unpin_elemental_pressure_dofs() [1/3]
template<unsigned DIM>
void oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::unpin_elemental_pressure_dofs () [inline], [private], [virtual]
Unpin all pressure dofs.
Implements oomph::RefineableSpaceTimeNavierStokesEquations< DIM >.
Definition at line 1191 of file refineable_discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::QTaylorHoodSpaceTimeElement< DIM >::p_nodal_index_nst(), and oomph::Data::unpin().
unpin_elemental_pressure_dofs() [2/3]
template<unsigned DIM>
void oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::unpin_elemental_pressure_dofs () [inline], [private], [virtual]
Unpin all pressure dofs.
Implements oomph::RefineableSpaceTimeNavierStokesEquations< DIM >.
Definition at line 1191 of file refineable_discontinuous_galerkin_spacetime_navier_stokes_elements.h.
References oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::QTaylorHoodSpaceTimeElement< DIM >::p_nodal_index_nst(), and oomph::Data::unpin().
unpin_elemental_pressure_dofs() [3/3]
template<unsigned DIM>
void oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::unpin_elemental_pressure_dofs () [inline], [private], [virtual]
Unpin all pressure dofs.
Implements oomph::RefineableSpaceTimeNavierStokesEquations< DIM >.
Definition at line 1191 of file refineable_spacetime_navier_stokes_elements.h.
References oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::QTaylorHoodSpaceTimeElement< DIM >::p_nodal_index_nst(), and oomph::Data::unpin().
vertex_node_pt() [1/3]
template<unsigned DIM>
Node * oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::vertex_node_pt (const unsigned & j) const [inline], [virtual]
Pointer to the j-th vertex node in the element.
Reimplemented from oomph::FiniteElement.
Definition at line 814 of file refineable_discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References oomph::FiniteElement::vertex_node_pt().
vertex_node_pt() [2/3]
template<unsigned DIM>
Node * oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::vertex_node_pt (const unsigned & j) const [inline], [virtual]
Pointer to the j-th vertex node in the element.
Reimplemented from oomph::FiniteElement.
Definition at line 814 of file refineable_discontinuous_galerkin_spacetime_navier_stokes_elements.h.
References oomph::FiniteElement::vertex_node_pt().
vertex_node_pt() [3/3]
template<unsigned DIM>
Node * oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::vertex_node_pt (const unsigned & j) const [inline], [virtual]
Pointer to the j-th vertex node in the element.
Reimplemented from oomph::FiniteElement.
Definition at line 814 of file refineable_spacetime_navier_stokes_elements.h.
References oomph::FiniteElement::vertex_node_pt().
The documentation for this class was generated from the following files:
refineable_discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h
refineable_discontinuous_galerkin_spacetime_navier_stokes_elements.h
refineable_spacetime_navier_stokes_elements.h