oomph::TetgenMesh< ELEMENT > Class Template Reference
Unstructured tet mesh based on output from Tetgen: http://wias-berlin.de/software/tetgen/.
#include <tetgen_mesh.template.h>
Public Member Functions
TetgenMesh ()
Empty constructor.
TetgenMesh (const std::string &node_file_name, const std::string &element_file_name, const std::string &face_file_name, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper, const bool &use_attributes=false)
Constructor with the input files.
TetgenMesh (tetgenio &tetgen_data, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper, const bool &use_attributes=false)
Constructor with tetgenio data structure.
TetgenMesh (const std::string &node_file_name, const std::string &element_file_name, const std::string &face_file_name, const bool &split_corner_elements, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper, const bool &use_attributes=false)
Constructor with the input files. Setting the boolean flag to true splits "corner" elements, i.e. elements that that have at least three faces on a domain boundary. The relevant elements are split without introducing hanging nodes so the sons have a "worse" shape than their fathers. However, this step avoids otherwise-hard-to-diagnose problems in fluids problems where the application of boundary conditions at such "corner" elements can overconstrain the solution.
TetgenMesh (tetgenio &tetgen_data, const bool &split_corner_elements, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper, const bool &use_attributes=false)
Constructor with tetgen data structure Setting the boolean flag to true splits "corner" elements, i.e. elements that that have at least three faces on a domain boundary. The relevant elements are split without introducing hanging nodes so the sons have a "worse" shape than their fathers. However, this step avoids otherwise-hard-to-diagnose problems in fluids problems where the application of boundary conditions at such "corner" elements can overconstrain the solution.
TetgenMesh (TetMeshFacetedClosedSurface *const &outer_boundary_pt, Vector< TetMeshFacetedSurface * > &internal_surface_pt, const double &element_volume, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper, const bool &use_attributes=false, const bool &split_corner_elements=false, Vector< double > *const &target_element_volume_in_region_pt=nullptr)
Build mesh, based on a TetgenMeshFactedClosedSurface that specifies the outer boundary of the domain and any number of internal boundaries, specified by TetMeshFacetedSurfaces. Also specify target size for uniform element size. Optionally specify the target element volume in each region.
void build_tetgenio (TetMeshFacetedSurface *const &outer_boundary_pt, Vector< TetMeshFacetedSurface * > &internal_surface_pt, Vector< double > *const &target_element_volume_in_region_pt, tetgenio &tetgen_io)
Build tetgenio object from the TetMeshFacetedSurfaces.
~TetgenMesh ()
Empty destructor.
void set_mesh_level_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Overload set_mesh_level_time_stepper so that the stored time stepper now corresponds to the new timestepper.
bool tetgenio_exists () const
Boolen defining whether tetgenio object has been built or not.
tetgenio *& tetgenio_pt ()
Access to the triangulateio representation of the mesh.
void set_deep_copy_tetgenio_pt (tetgenio *const &tetgenio_pt)
Set the tetgen pointer by a deep copy.
void deep_copy_of_tetgenio (tetgenio *const &input_pt, tetgenio *&output_pt)
Transfer tetgenio data from the input to the output The output is assumed to have been constructed and "empty".
Protected Member Functions
void build_from_scaffold (TimeStepper *time_stepper_pt, const bool &use_attributes)
Build mesh from scaffold.
void setup_reverse_lookup_schemes_for_faceted_surface (TetMeshFacetedSurface *const &faceted_surface_pt)
Function to setup the reverse look-up schemes.
Protected Attributes
TetgenScaffoldMesh * Tmp_mesh_pt
Temporary scaffold mesh.
bool Tetgenio_exists
Boolean to indicate whether a tetgenio representation of the mesh exists.
tetgenio * Tetgenio_pt
Tetgen representation of mesh.
bool Use_attributes
Boolean flag to indicate whether to use attributes or not (required for multidomain meshes)
Detailed Description
template<class ELEMENT>
class oomph::TetgenMesh< ELEMENT >
Unstructured tet mesh based on output from Tetgen: http://wias-berlin.de/software/tetgen/.
Definition at line 51 of file tetgen_mesh.template.h.
Constructor & Destructor Documentation
TetgenMesh() [1/6]
template<class ELEMENT >
oomph::TetgenMesh< ELEMENT >::TetgenMesh () [inline]
Empty constructor.
Definition at line 55 of file tetgen_mesh.template.h.
Referenced by NavierStokesProblem< ELEMENT >::actions_before_newton_solve(), oomph::RefineableGmshTetMesh< ELEMENT >::adapt(), oomph::RefineableQuadFromTriangleMesh< ELEMENT >::adapt(), oomph::RefineableTetgenMesh< ELEMENT >::adapt(), oomph::RefineableTriangleMesh< ELEMENT >::adapt(), oomph::RefineableTriangleMesh< ELEMENT >::add_element_load_balance_helper(), oomph::RefineableTriangleMesh< ELEMENT >::add_halo_element_helper(), oomph::RefineableTriangleMesh< ELEMENT >::add_halo_node_helper(), oomph::RefineableTriangleMesh< ELEMENT >::add_haloed_node_helper(), oomph::RefineableTriangleMesh< ELEMENT >::add_node_load_balance_helper(), oomph::RefineableTriangleMesh< ELEMENT >::add_non_delete_vertices_from_boundary_helper(), oomph::RefineableTriangleMesh< ELEMENT >::add_received_node_load_balance_helper(), oomph::RefineableTriangleMesh< ELEMENT >::add_vertices_for_non_deletion(), oomph::AlgebraicChannelWithLeafletMesh< ELEMENT >::algebraic_node_update(), oomph::AlgebraicCollapsibleChannelMesh< ELEMENT >::algebraic_node_update(), oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::algebraic_node_update(), oomph::AlgebraicFSIDrivenCavityMesh< ELEMENT >::algebraic_node_update(), oomph::RefineableTriangleMesh< ELEMENT >::apply_max_length_constraint(), oomph::OneDLagrangianMesh< ELEMENT >::assign_default_element_gradients(), oomph::OneDLagrangianMesh< ELEMENT >::assign_undeformed_positions(), oomph::CircularCylindricalShellMesh< ELEMENT >::assign_undeformed_positions(), oomph::TriangleMesh< ELEMENT >::break_loops_on_shared_polyline_helper(), oomph::TriangleMesh< ELEMENT >::break_loops_on_shared_polyline_load_balance_helper(), oomph::ChannelSpineMesh< ELEMENT >::build_channel_spine_mesh(), oomph::GeompackQuadMesh< ELEMENT >::build_from_scaffold(), oomph::SimpleCubicTetMesh< ELEMENT >::build_from_scaffold(), oomph::TetgenMesh< ELEMENT >::build_from_scaffold(), oomph::TriangleMesh< ELEMENT >::build_from_scaffold(), oomph::QuadFromTriangleMesh< ELEMENT >::build_from_scaffold(), oomph::CircularCylindricalShellMesh< ELEMENT >::build_mesh(), oomph::BackwardStepQuadMesh< ELEMENT >::build_mesh(), oomph::ExtrudedCubeMeshFromQuadMesh< ELEMENT >::build_mesh(), oomph::BrickFromTetMesh< ELEMENT >::build_mesh(), oomph::FishMesh< ELEMENT >::build_mesh(), oomph::HermiteQuadMesh< ELEMENT >::build_mesh(), oomph::OneDMesh< ELEMENT >::build_mesh(), oomph::RectangularQuadMesh< ELEMENT >::build_mesh(), oomph::SimpleCubicMesh< ELEMENT >::build_mesh(), oomph::BrickFromTetMesh< ELEMENT >::build_mesh(), oomph::SingleLayerCubicSpineMesh< ELEMENT >::build_single_layer_mesh(), oomph::SingleLayerSpineMesh< ELEMENT >::build_single_layer_mesh(), oomph::TetgenMesh< ELEMENT >::build_tetgenio(), oomph::TriangleMesh< ELEMENT >::build_triangulateio(), oomph::TwoLayerSpineMesh< ELEMENT >::build_two_layer_mesh(), oomph::TriangleMesh< ELEMENT >::check_connections_of_polyline_nodes(), oomph::TriangleMesh< ELEMENT >::compute_boundary_segments_connectivity_and_initial_zeta_values(), oomph::RefineableTriangleMesh< ELEMENT >::compute_global_node_names_and_shared_nodes(), oomph::TriangleMesh< ELEMENT >::compute_holes_left_by_halo_elements_helper(), oomph::RefineableTriangleMesh< ELEMENT >::compute_shared_node_degree_helper(), oomph::RefineableTriangleMesh< ELEMENT >::construct_new_halo_node_helper(), oomph::RefineableTriangleMesh< ELEMENT >::construct_new_node_load_balance_helper(), oomph::RefineableTriangleMesh< ELEMENT >::create_adjacency_matrix_new_shared_edges_helper(), oomph::TriangleMesh< ELEMENT >::create_distributed_domain_representation(), oomph::RefineableTriangleMesh< ELEMENT >::create_element_load_balance_helper(), oomph::RefineableTriangleMesh< ELEMENT >::create_halo_element(), oomph::RefineableTriangleMesh< ELEMENT >::create_new_shared_boundaries(), oomph::TriangleMesh< ELEMENT >::create_polylines_from_halo_elements_helper(), oomph::RefineableTriangleMesh< ELEMENT >::create_polylines_from_polyfiles(), oomph::TriangleMesh< ELEMENT >::create_shared_boundaries(), oomph::TriangleMesh< ELEMENT >::create_shared_polyline(), oomph::TriangleMesh< ELEMENT >::create_shared_polylines_connections(), oomph::RefineableTriangleMesh< ELEMENT >::create_sorted_face_mesh_representation(), oomph::RefineableTriangleMesh< ELEMENT >::create_temporary_boundary_connections(), oomph::TriangleMesh< ELEMENT >::create_tmp_open_curves_helper(), oomph::TriangleMesh< ELEMENT >::create_tmp_polygons_helper(), oomph::RefineableTriangleMesh< ELEMENT >::create_unsorted_face_mesh_representation(), oomph::CylinderWithFlagMesh< ELEMENT >::CylinderWithFlagMesh(), oomph::TetgenMesh< ELEMENT >::deep_copy_of_tetgenio(), NavierStokesProblem< ELEMENT >::doc_solution(), PoissonProblem< ELEMENT >::doc_solution(), oomph::TriangleMesh< ELEMENT >::dump_distributed_info_for_restart(), oomph::ChannelSpineMesh< ELEMENT >::element_reorder(), oomph::RectangularQuadMesh< ELEMENT >::element_reorder(), oomph::RefineableTriangleMesh< ELEMENT >::fill_boundary_elements_and_nodes_for_internal_boundaries(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::find_distance_to_free_surface(), oomph::FishMesh< ELEMENT >::FishMesh(), oomph::HermiteQuadMesh< ELEMENT >::generalised_macro_element_position_of_node(), oomph::RefineableTriangleMesh< ELEMENT >::get_boundary_segment_nodes_helper(), oomph::RefineableTriangleMesh< ELEMENT >::get_connected_vertex_number_on_dst_boundary(), oomph::TriangleMesh< ELEMENT >::get_element_edges_on_boundary(), oomph::RefineableTriangleMesh< ELEMENT >::get_face_mesh_representation(), oomph::RefineableTriangleMesh< ELEMENT >::get_face_mesh_representation(), oomph::TriangleMesh< ELEMENT >::get_halo_elements_on_all_procs(), oomph::RefineableTriangleMesh< ELEMENT >::get_required_elemental_information_load_balance_helper(), oomph::RefineableTriangleMesh< ELEMENT >::get_required_nodal_information_helper(), oomph::RefineableTriangleMesh< ELEMENT >::get_required_nodal_information_load_balance_helper(), oomph::RefineableTriangleMesh< ELEMENT >::get_shared_boundary_elements_and_face_indexes(), oomph::RefineableTriangleMesh< ELEMENT >::get_shared_boundary_segment_nodes_helper(), oomph::TriangleMesh< ELEMENT >::identify_boundary_segments_and_assign_initial_zeta_values(), oomph::RefineableTriangleMesh< ELEMENT >::load_balance(), oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::node_update_central_region(), oomph::AlgebraicChannelWithLeafletMesh< ELEMENT >::node_update_I(), oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::node_update_I(), oomph::AlgebraicChannelWithLeafletMesh< ELEMENT >::node_update_II(), oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::node_update_II(), oomph::AlgebraicChannelWithLeafletMesh< ELEMENT >::node_update_III(), oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::node_update_III(), oomph::AlgebraicFishMesh< ELEMENT >::node_update_in_body(), oomph::AlgebraicFishMesh< ELEMENT >::node_update_in_fin(), oomph::AlgebraicChannelWithLeafletMesh< ELEMENT >::node_update_IV(), oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::node_update_IV(), oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::node_update_IX(), oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::node_update_V(), oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::node_update_VI(), oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::node_update_VII(), oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::node_update_VIII(), oomph::TriangleMesh< ELEMENT >::output_boundary_coordinates(), oomph::TriangleMesh< ELEMENT >::re_assign_initial_zeta_values_for_internal_boundary(), oomph::TriangleMesh< ELEMENT >::re_scale_re_assigned_initial_zeta_values_for_internal_boundary(), oomph::TriangleMesh< ELEMENT >::read_distributed_info_for_restart(), oomph::RectangleWithHoleAndAnnularRegionMesh< ELEMENT >::RectangleWithHoleAndAnnularRegionMesh(), oomph::RefineableTriangleMesh< ELEMENT >::refine_boundary(), oomph::RefineableTriangleMesh< ELEMENT >::refine_boundary_constrained_by_target_area(), oomph::RefineableTriangleMesh< ELEMENT >::refine_shared_boundary_constrained_by_target_area(), oomph::RefineableTriangleMesh< ELEMENT >::refine_triangulateio(), oomph::RefineableTetgenMesh< ELEMENT >::refine_uniformly(), oomph::RefineableQuadMeshWithMovingCylinder< ELEMENT >::RefineableQuadMeshWithMovingCylinder(), oomph::RefineableTetgenMesh< ELEMENT >::RefineableTetgenMesh(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::reposition_spines(), oomph::TriangleMesh< ELEMENT >::reset_boundary_element_info(), oomph::RefineableTriangleMesh< ELEMENT >::reset_halo_haloed_scheme(), oomph::RefineableTriangleMesh< ELEMENT >::reset_halo_haloed_scheme_helper(), oomph::RefineableTriangleMesh< ELEMENT >::reset_shared_boundary_elements_and_nodes(), oomph::RefineableTriangleMesh< ELEMENT >::restore_boundary_connections(), oomph::RefineableTriangleMesh< ELEMENT >::restore_polyline_connections_helper(), oomph::RefineableTriangleMesh< ELEMENT >::resume_boundary_connections(), oomph::TriangleMesh< ELEMENT >::select_boundary_face_elements(), oomph::RefineableTriangleMesh< ELEMENT >::send_and_receive_elements_nodes_info(), oomph::RefineableTriangleMesh< ELEMENT >::send_boundary_node_info_of_shared_nodes(), oomph::TetgenMesh< ELEMENT >::set_deep_copy_tetgenio_pt(), oomph::TetgenMesh< ELEMENT >::set_mesh_level_time_stepper(), oomph::HermiteQuadMesh< ELEMENT >::set_position_of_boundary_node(), oomph::HermiteQuadMesh< ELEMENT >::set_position_of_node(), oomph::RefineableFishMesh< ELEMENT >::setup_adaptivity(), oomph::AlgebraicChannelWithLeafletMesh< ELEMENT >::setup_algebraic_node_update(), oomph::AlgebraicCollapsibleChannelMesh< ELEMENT >::setup_algebraic_node_update(), oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::setup_algebraic_node_update(), oomph::AlgebraicFishMesh< ELEMENT >::setup_algebraic_node_update(), oomph::AlgebraicFSIDrivenCavityMesh< ELEMENT >::setup_algebraic_node_update(), oomph::XdaTetMesh< ELEMENT >::setup_boundary_coordinates(), oomph::HermiteQuadMesh< ELEMENT >::setup_boundary_element_info(), oomph::TetgenMesh< ELEMENT >::setup_reverse_lookup_schemes_for_faceted_surface(), oomph::SimpleRectangularQuadMesh< ELEMENT >::SimpleRectangularQuadMesh(), oomph::AlgebraicChannelWithLeafletMesh< ELEMENT >::slanted_bound_up(), oomph::RefineableTetgenMesh< ELEMENT >::snap_nodes_onto_boundary(), oomph::RefineableTriangleMesh< ELEMENT >::snap_nodes_onto_boundary(), oomph::SolidTetgenMesh< ELEMENT >::SolidTetgenMesh(), oomph::SolidTetgenMesh< ELEMENT >::SolidTetgenMesh(), oomph::RefineableTriangleMesh< ELEMENT >::sort_nodes_on_shared_boundaries(), oomph::TriangleMesh< ELEMENT >::sort_polylines_helper(), oomph::RefineableTetgenMesh< ELEMENT >::surface_remesh_for_inner_hole_boundaries(), oomph::TriangleMesh< ELEMENT >::synchronize_boundary_coordinates(), oomph::TetgenMesh< ELEMENT >::TetgenMesh(), oomph::TetgenMesh< ELEMENT >::TetgenMesh(), oomph::TetgenMesh< ELEMENT >::TetgenMesh(), oomph::TetgenMesh< ELEMENT >::TetgenMesh(), oomph::TetgenMesh< ELEMENT >::TetgenMesh(), oomph::RefineableTriangleMesh< ELEMENT >::unrefine_boundary(), oomph::RefineableTriangleMesh< ELEMENT >::unrefine_boundary_constrained_by_target_area(), oomph::RefineableTriangleMesh< ELEMENT >::unrefine_shared_boundary_constrained_by_target_area(), oomph::RefineableTetgenMesh< ELEMENT >::unrefine_uniformly(), oomph::RefineableTetgenMesh< ELEMENT >::update_faceted_surface_using_face_mesh(), oomph::TriangleMesh< ELEMENT >::update_holes_information_helper(), oomph::RefineableAlgebraicChannelWithLeafletMesh< ELEMENT >::update_node_update(), oomph::RefineableAlgebraicCollapsibleChannelMesh< ELEMENT >::update_node_update(), oomph::RefineableAlgebraicCylinderWithFlagMesh< ELEMENT >::update_node_update(), oomph::RefineableAlgebraicFSIDrivenCavityMesh< ELEMENT >::update_node_update(), oomph::RefineableTriangleMesh< ELEMENT >::update_open_curve_after_restart(), oomph::RefineableTriangleMesh< ELEMENT >::update_open_curve_using_elements_area(), oomph::RefineableTriangleMesh< ELEMENT >::update_open_curve_using_face_mesh(), oomph::RefineableTriangleMesh< ELEMENT >::update_other_proc_shd_bnd_node_helper(), oomph::RefineableTriangleMesh< ELEMENT >::update_polygon_after_restart(), oomph::RefineableTriangleMesh< ELEMENT >::update_polygon_using_elements_area(), oomph::RefineableTriangleMesh< ELEMENT >::update_polygon_using_face_mesh(), oomph::RefineableTriangleMesh< ELEMENT >::update_shared_curve_after_restart(), oomph::RefineableTriangleMesh< ELEMENT >::update_shared_curve_using_elements_area(), oomph::TwoDAnnularMesh< ELEMENT >::wrap_into_annular_shape(), oomph::XdaTetMesh< ELEMENT >::XdaTetMesh(), and oomph::TwoLayerSpineMesh< ELEMENT >::y_spacing_function().
TetgenMesh() [2/6]
template<class ELEMENT >
oomph::TetgenMesh< ELEMENT >::TetgenMesh (const std::string & node_file_name, const std::string & element_file_name, const std::string & face_file_name, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper, const bool & use_attributes = false) [inline]
Constructor with the input files.
Definition at line 62 of file tetgen_mesh.template.h.
References oomph::TetgenMesh< ELEMENT >::build_from_scaffold(), oomph::TetgenMesh< ELEMENT >::TetgenMesh(), oomph::TetgenMesh< ELEMENT >::Tmp_mesh_pt, and oomph::TetgenMesh< ELEMENT >::Use_attributes.
TetgenMesh() [3/6]
template<class ELEMENT >
oomph::TetgenMesh< ELEMENT >::TetgenMesh (tetgenio & tetgen_data, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper, const bool & use_attributes = false) [inline]
Constructor with tetgenio data structure.
Definition at line 100 of file tetgen_mesh.template.h.
References oomph::TetgenMesh< ELEMENT >::build_from_scaffold(), oomph::TetgenMesh< ELEMENT >::Tetgenio_exists, oomph::TetgenMesh< ELEMENT >::Tetgenio_pt, oomph::TetgenMesh< ELEMENT >::TetgenMesh(), oomph::TetgenMesh< ELEMENT >::Tmp_mesh_pt, and oomph::TetgenMesh< ELEMENT >::Use_attributes.
TetgenMesh() [4/6]
template<class ELEMENT >
oomph::TetgenMesh< ELEMENT >::TetgenMesh (const std::string & node_file_name, const std::string & element_file_name, const std::string & face_file_name, const bool & split_corner_elements, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper, const bool & use_attributes = false) [inline]
Constructor with the input files. Setting the boolean flag to true splits "corner" elements, i.e. elements that that have at least three faces on a domain boundary. The relevant elements are split without introducing hanging nodes so the sons have a "worse" shape than their fathers. However, this step avoids otherwise-hard-to-diagnose problems in fluids problems where the application of boundary conditions at such "corner" elements can overconstrain the solution.
Definition at line 147 of file tetgen_mesh.template.h.
References oomph::TetgenMesh< ELEMENT >::build_from_scaffold(), oomph::TetgenMesh< ELEMENT >::Tetgenio_exists, oomph::TetgenMesh< ELEMENT >::Tetgenio_pt, oomph::TetgenMesh< ELEMENT >::TetgenMesh(), oomph::TetgenMesh< ELEMENT >::Tmp_mesh_pt, and oomph::TetgenMesh< ELEMENT >::Use_attributes.
TetgenMesh() [5/6]
template<class ELEMENT >
oomph::TetgenMesh< ELEMENT >::TetgenMesh (tetgenio & tetgen_data, const bool & split_corner_elements, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper, const bool & use_attributes = false) [inline]
Constructor with tetgen data structure Setting the boolean flag to true splits "corner" elements, i.e. elements that that have at least three faces on a domain boundary. The relevant elements are split without introducing hanging nodes so the sons have a "worse" shape than their fathers. However, this step avoids otherwise-hard-to-diagnose problems in fluids problems where the application of boundary conditions at such "corner" elements can overconstrain the solution.
Definition at line 203 of file tetgen_mesh.template.h.
References oomph::TetgenMesh< ELEMENT >::build_from_scaffold(), oomph::TetgenMesh< ELEMENT >::Tetgenio_exists, oomph::TetgenMesh< ELEMENT >::Tetgenio_pt, oomph::TetgenMesh< ELEMENT >::TetgenMesh(), oomph::TetgenMesh< ELEMENT >::Tmp_mesh_pt, and oomph::TetgenMesh< ELEMENT >::Use_attributes.
TetgenMesh() [6/6]
template<class ELEMENT >
oomph::TetgenMesh< ELEMENT >::TetgenMesh (TetMeshFacetedClosedSurface *const & outer_boundary_pt, Vector< TetMeshFacetedSurface * > & internal_surface_pt, const double & element_volume, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper, const bool & use_attributes = false, const bool & split_corner_elements = false, Vector< double > *const & target_element_volume_in_region_pt = nullptr) [inline]
Build mesh, based on a TetgenMeshFactedClosedSurface that specifies the outer boundary of the domain and any number of internal boundaries, specified by TetMeshFacetedSurfaces. Also specify target size for uniform element size. Optionally specify the target element volume in each region.
Definition at line 253 of file tetgen_mesh.template.h.
References oomph::TetgenMesh< ELEMENT >::build_from_scaffold(), oomph::TetgenMesh< ELEMENT >::build_tetgenio(), oomph::TetgenMesh< ELEMENT >::setup_reverse_lookup_schemes_for_faceted_surface(), oomph::TetgenMesh< ELEMENT >::Tetgenio_exists, oomph::TetgenMesh< ELEMENT >::Tetgenio_pt, oomph::TetgenMesh< ELEMENT >::TetgenMesh(), oomph::TetgenMesh< ELEMENT >::Tmp_mesh_pt, and oomph::TetgenMesh< ELEMENT >::Use_attributes.
~TetgenMesh()
template<class ELEMENT >
oomph::TetgenMesh< ELEMENT >::~TetgenMesh () [inline]
Empty destructor.
Definition at line 653 of file tetgen_mesh.template.h.
References oomph::TetgenMesh< ELEMENT >::Tetgenio_exists, and oomph::TetgenMesh< ELEMENT >::Tetgenio_pt.
Member Function Documentation
build_from_scaffold()
template<class ELEMENT >
void oomph::TetgenMesh< ELEMENT >::build_from_scaffold (TimeStepper * time_stepper_pt, const bool & use_attributes) [protected]
Build mesh from scaffold.
//////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
Build unstructured tet mesh based on output from scaffold
Definition at line 48 of file tetgen_mesh.template.cc.
References oomph::TetgenMesh< ELEMENT >::TetgenMesh(), and oomph::TetgenMesh< ELEMENT >::Tmp_mesh_pt.
Referenced by oomph::RefineableTetgenMesh< ELEMENT >::RefineableTetgenMesh(), oomph::TetgenMesh< ELEMENT >::TetgenMesh(), oomph::TetgenMesh< ELEMENT >::TetgenMesh(), oomph::TetgenMesh< ELEMENT >::TetgenMesh(), oomph::TetgenMesh< ELEMENT >::TetgenMesh(), and oomph::TetgenMesh< ELEMENT >::TetgenMesh().
build_tetgenio()
template<class ELEMENT >
void oomph::TetgenMesh< ELEMENT >::build_tetgenio (TetMeshFacetedSurface *const & outer_boundary_pt, Vector< TetMeshFacetedSurface * > & internal_surface_pt, Vector< double > *const & target_element_volume_in_region_pt, tetgenio & tetgen_io) [inline]
Build tetgenio object from the TetMeshFacetedSurfaces.
ALH: This may not be needed
Definition at line 397 of file tetgen_mesh.template.h.
References oomph::TetgenMesh< ELEMENT >::TetgenMesh().
Referenced by oomph::TetgenMesh< ELEMENT >::TetgenMesh().
deep_copy_of_tetgenio()
template<class ELEMENT >
void oomph::TetgenMesh< ELEMENT >::deep_copy_of_tetgenio (tetgenio *const & input_pt, tetgenio *& output_pt)
Transfer tetgenio data from the input to the output The output is assumed to have been constructed and "empty".
//////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
Transfer tetgenio data from the input to the output The output is assumed to have been constructed and "empty"
Definition at line 865 of file tetgen_mesh.template.cc.
References oomph::TetgenMesh< ELEMENT >::TetgenMesh().
Referenced by oomph::RefineableTetgenMesh< ELEMENT >::RefineableTetgenMesh(), and oomph::TetgenMesh< ELEMENT >::set_deep_copy_tetgenio_pt().
set_deep_copy_tetgenio_pt()
template<class ELEMENT >
void oomph::TetgenMesh< ELEMENT >::set_deep_copy_tetgenio_pt (tetgenio *const & tetgenio_pt) [inline]
Set the tetgen pointer by a deep copy.
Definition at line 685 of file tetgen_mesh.template.h.
References oomph::TetgenMesh< ELEMENT >::deep_copy_of_tetgenio(), oomph::TetgenMesh< ELEMENT >::Tetgenio_exists, oomph::TetgenMesh< ELEMENT >::Tetgenio_pt, and oomph::TetgenMesh< ELEMENT >::TetgenMesh().
Referenced by oomph::RefineableTetgenMesh< ELEMENT >::adapt().
set_mesh_level_time_stepper()
template<class ELEMENT >
void oomph::TetgenMesh< ELEMENT >::set_mesh_level_time_stepper (TimeStepper *const & time_stepper_pt, const bool & preserve_existing_data) [inline]
Overload set_mesh_level_time_stepper so that the stored time stepper now corresponds to the new timestepper.
Definition at line 664 of file tetgen_mesh.template.h.
References oomph::TetgenMesh< ELEMENT >::TetgenMesh().
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::adapt().
setup_reverse_lookup_schemes_for_faceted_surface()
template<class ELEMENT >
void oomph::TetgenMesh< ELEMENT >::setup_reverse_lookup_schemes_for_faceted_surface (TetMeshFacetedSurface *const & faceted_surface_pt) [protected]
Function to setup the reverse look-up schemes.
Helper function to set up the reverse look up scheme for facets. This is used to set up boundary coordinates.
Definition at line 828 of file tetgen_mesh.template.cc.
References oomph::TetgenMesh< ELEMENT >::TetgenMesh().
Referenced by oomph::RefineableTetgenMesh< ELEMENT >::RefineableTetgenMesh(), oomph::TetgenMesh< ELEMENT >::TetgenMesh(), and oomph::RefineableTetgenMesh< ELEMENT >::update_faceted_surface_using_face_mesh().
tetgenio_exists()
template<class ELEMENT >
bool oomph::TetgenMesh< ELEMENT >::tetgenio_exists () const [inline]
Boolen defining whether tetgenio object has been built or not.
Definition at line 672 of file tetgen_mesh.template.h.
References oomph::TetgenMesh< ELEMENT >::Tetgenio_exists.
tetgenio_pt()
template<class ELEMENT >
tetgenio *& oomph::TetgenMesh< ELEMENT >::tetgenio_pt () [inline]
Access to the triangulateio representation of the mesh.
Definition at line 679 of file tetgen_mesh.template.h.
References oomph::TetgenMesh< ELEMENT >::Tetgenio_pt.
Referenced by oomph::RefineableTetgenMesh< ELEMENT >::adapt().
Member Data Documentation
Tetgenio_exists
template<class ELEMENT >
bool oomph::TetgenMesh< ELEMENT >::Tetgenio_exists [protected]
Boolean to indicate whether a tetgenio representation of the mesh exists.
Definition at line 717 of file tetgen_mesh.template.h.
Referenced by oomph::RefineableTetgenMesh< ELEMENT >::RefineableTetgenMesh(), oomph::TetgenMesh< ELEMENT >::set_deep_copy_tetgenio_pt(), oomph::TetgenMesh< ELEMENT >::tetgenio_exists(), oomph::TetgenMesh< ELEMENT >::TetgenMesh(), oomph::TetgenMesh< ELEMENT >::TetgenMesh(), oomph::TetgenMesh< ELEMENT >::TetgenMesh(), oomph::TetgenMesh< ELEMENT >::TetgenMesh(), and oomph::TetgenMesh< ELEMENT >::~TetgenMesh().
Tetgenio_pt
template<class ELEMENT >
tetgenio* oomph::TetgenMesh< ELEMENT >::Tetgenio_pt [protected]
Tetgen representation of mesh.
Definition at line 720 of file tetgen_mesh.template.h.
Referenced by oomph::RefineableTetgenMesh< ELEMENT >::RefineableTetgenMesh(), oomph::TetgenMesh< ELEMENT >::set_deep_copy_tetgenio_pt(), oomph::TetgenMesh< ELEMENT >::tetgenio_pt(), oomph::TetgenMesh< ELEMENT >::TetgenMesh(), oomph::TetgenMesh< ELEMENT >::TetgenMesh(), oomph::TetgenMesh< ELEMENT >::TetgenMesh(), oomph::TetgenMesh< ELEMENT >::TetgenMesh(), and oomph::TetgenMesh< ELEMENT >::~TetgenMesh().
Tmp_mesh_pt
template<class ELEMENT >
TetgenScaffoldMesh* oomph::TetgenMesh< ELEMENT >::Tmp_mesh_pt [protected]
Temporary scaffold mesh.
Definition at line 713 of file tetgen_mesh.template.h.
Referenced by oomph::GeompackQuadMesh< ELEMENT >::build_from_scaffold(), oomph::SimpleCubicTetMesh< ELEMENT >::build_from_scaffold(), oomph::TetgenMesh< ELEMENT >::build_from_scaffold(), oomph::TriangleMesh< ELEMENT >::build_from_scaffold(), oomph::RefineableTetgenMesh< ELEMENT >::RefineableTetgenMesh(), oomph::TetgenMesh< ELEMENT >::TetgenMesh(), oomph::TetgenMesh< ELEMENT >::TetgenMesh(), oomph::TetgenMesh< ELEMENT >::TetgenMesh(), oomph::TetgenMesh< ELEMENT >::TetgenMesh(), and oomph::TetgenMesh< ELEMENT >::TetgenMesh().
Use_attributes
template<class ELEMENT >
bool oomph::TetgenMesh< ELEMENT >::Use_attributes [protected]
Boolean flag to indicate whether to use attributes or not (required for multidomain meshes)
Definition at line 724 of file tetgen_mesh.template.h.
Referenced by oomph::RefineableTetgenMesh< ELEMENT >::adapt(), oomph::RefineableTriangleMesh< ELEMENT >::adapt(), oomph::TetgenMesh< ELEMENT >::TetgenMesh(), oomph::TetgenMesh< ELEMENT >::TetgenMesh(), oomph::TetgenMesh< ELEMENT >::TetgenMesh(), oomph::TetgenMesh< ELEMENT >::TetgenMesh(), and oomph::TetgenMesh< ELEMENT >::TetgenMesh().
The documentation for this class was generated from the following files:
tetgen_mesh.template.h
tetgen_mesh.template.cc