RefineableFishPoissonProblem< ELEMENT > Class Template Reference
///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
Public Member Functions
RefineableFishPoissonProblem (const bool &fix_position, string directory_name)
Constructor: Bool flag specifies if position of fish back is prescribed or computed from the coupled problem. String specifies output directory.
virtual ~RefineableFishPoissonProblem ()
Destructor.
void actions_before_newton_convergence_check ()
Update after Newton step: Update mesh in response to possible changes in the wall shape.
void actions_after_newton_solve ()
Update the problem specs after solve (empty)
void actions_before_newton_solve ()
Update the problem specs before solve: Update mesh.
AlgebraicRefineableFishMesh< ELEMENT > * fish_mesh_pt ()
double & load ()
Return value of the "load" on the elastically supported ring.
void doc_solution ()
Doc the solution.
DocInfo & doc_info ()
Access to DocInfo object.
Private Attributes
Node * Doc_node_pt
Node at which the solution of the Poisson equation is documented.
ofstream Trace_file
Trace file.
AlgebraicRefineableFishMesh< ELEMENT > * Fish_mesh_pt
Pointer to fish mesh.
Mesh * Fish_back_mesh_pt
Pointer to single-element mesh that stores the GeneralisedElement that represents the fish back.
Data * Load_pt
Pointer to data item that stores the "load" on the fish back.
bool Fix_position
Is the position of the fish back prescribed?
DocInfo Doc_info
Doc info object.
Detailed Description
template<class ELEMENT>
class RefineableFishPoissonProblem< ELEMENT >
///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
Fish back as a GeneralisedElement: Circular ring whose position is given by
 x = X_c + R \cos(\xi)  
 y = Y_c + R \sin(\xi)  
 The ring's vertical position $ Y_c $ is determined by "pseudo elasticity": ///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// Refineable Poisson problem in deformable fish-shaped domain. Template parameter identify the elements.
Definition at line 243 of file elastic_poisson.cc.
Constructor & Destructor Documentation
RefineableFishPoissonProblem()
template<class ELEMENT >
RefineableFishPoissonProblem< ELEMENT >::RefineableFishPoissonProblem (const bool & fix_position, string directory_name)
Constructor: Bool flag specifies if position of fish back is prescribed or computed from the coupled problem. String specifies output directory.
Constructor for adaptive Poisson problem in deformable fish-shaped domain. Pass flag if position of fish back is fixed, and the output directory. Loop over elements and set pointers to source function
Definition at line 326 of file elastic_poisson.cc.
References RefineableFishPoissonProblem< ELEMENT >::Doc_info, RefineableFishPoissonProblem< ELEMENT >::Doc_node_pt, RefineableFishPoissonProblem< ELEMENT >::Fish_back_mesh_pt, RefineableFishPoissonProblem< ELEMENT >::fish_mesh_pt(), RefineableFishPoissonProblem< ELEMENT >::Fish_mesh_pt, RefineableFishPoissonProblem< ELEMENT >::Fix_position, ConstSourceForPoisson::get_source(), RefineableFishPoissonProblem< ELEMENT >::Load_pt, and RefineableFishPoissonProblem< ELEMENT >::Trace_file.
~RefineableFishPoissonProblem()
template<class ELEMENT >
RefineableFishPoissonProblem< ELEMENT >::~RefineableFishPoissonProblem () [virtual]
Destructor.
Destructor for Poisson problem in deformable fish-shaped domain.
Definition at line 468 of file elastic_poisson.cc.
Member Function Documentation
actions_after_newton_solve()
template<class ELEMENT >
void RefineableFishPoissonProblem< ELEMENT >::actions_after_newton_solve () [inline]
Update the problem specs after solve (empty)
Definition at line 264 of file elastic_poisson.cc.
actions_before_newton_convergence_check()
template<class ELEMENT >
void RefineableFishPoissonProblem< ELEMENT >::actions_before_newton_convergence_check () [inline]
Update after Newton step: Update mesh in response to possible changes in the wall shape.
Definition at line 258 of file elastic_poisson.cc.
References RefineableFishPoissonProblem< ELEMENT >::fish_mesh_pt().
actions_before_newton_solve()
template<class ELEMENT >
void RefineableFishPoissonProblem< ELEMENT >::actions_before_newton_solve () [inline]
Update the problem specs before solve: Update mesh.
Definition at line 267 of file elastic_poisson.cc.
References RefineableFishPoissonProblem< ELEMENT >::fish_mesh_pt().
doc_info()
template<class ELEMENT >
DocInfo & RefineableFishPoissonProblem< ELEMENT >::doc_info () [inline]
Access to DocInfo object.
Definition at line 288 of file elastic_poisson.cc.
References RefineableFishPoissonProblem< ELEMENT >::Doc_info.
Referenced by demo_fish_poisson().
doc_solution()
template<class ELEMENT >
void RefineableFishPoissonProblem< ELEMENT >::doc_solution ()
Doc the solution.
Doc the solution in tecplot format.
Definition at line 481 of file elastic_poisson.cc.
Referenced by demo_elastic_fish_poisson(), and demo_fish_poisson().
fish_mesh_pt()
template<class ELEMENT >
AlgebraicRefineableFishMesh< ELEMENT > * RefineableFishPoissonProblem< ELEMENT >::fish_mesh_pt () [inline]
Definition at line 273 of file elastic_poisson.cc.
References RefineableFishPoissonProblem< ELEMENT >::Fish_mesh_pt.
Referenced by RefineableFishPoissonProblem< ELEMENT >::actions_before_newton_convergence_check(), RefineableFishPoissonProblem< ELEMENT >::actions_before_newton_solve(), demo_elastic_fish_poisson(), demo_fish_poisson(), and RefineableFishPoissonProblem< ELEMENT >::RefineableFishPoissonProblem().
load()
template<class ELEMENT >
double & RefineableFishPoissonProblem< ELEMENT >::load () [inline]
Return value of the "load" on the elastically supported ring.
Definition at line 279 of file elastic_poisson.cc.
References RefineableFishPoissonProblem< ELEMENT >::Load_pt.
Referenced by demo_elastic_fish_poisson(), and demo_fish_poisson().
Member Data Documentation
Doc_info
template<class ELEMENT >
DocInfo RefineableFishPoissonProblem< ELEMENT >::Doc_info [private]
Doc info object.
Definition at line 312 of file elastic_poisson.cc.
Referenced by RefineableFishPoissonProblem< ELEMENT >::doc_info(), and RefineableFishPoissonProblem< ELEMENT >::RefineableFishPoissonProblem().
Doc_node_pt
template<class ELEMENT >
Node* RefineableFishPoissonProblem< ELEMENT >::Doc_node_pt [private]
Node at which the solution of the Poisson equation is documented.
Definition at line 293 of file elastic_poisson.cc.
Referenced by RefineableFishPoissonProblem< ELEMENT >::RefineableFishPoissonProblem().
Fish_back_mesh_pt
template<class ELEMENT >
Mesh* RefineableFishPoissonProblem< ELEMENT >::Fish_back_mesh_pt [private]
Pointer to single-element mesh that stores the GeneralisedElement that represents the fish back.
Definition at line 303 of file elastic_poisson.cc.
Referenced by RefineableFishPoissonProblem< ELEMENT >::RefineableFishPoissonProblem().
Fish_mesh_pt
template<class ELEMENT >
AlgebraicRefineableFishMesh<ELEMENT>* RefineableFishPoissonProblem< ELEMENT >::Fish_mesh_pt [private]
Pointer to fish mesh.
Definition at line 299 of file elastic_poisson.cc.
Referenced by RefineableFishPoissonProblem< ELEMENT >::fish_mesh_pt(), and RefineableFishPoissonProblem< ELEMENT >::RefineableFishPoissonProblem().
Fix_position
template<class ELEMENT >
bool RefineableFishPoissonProblem< ELEMENT >::Fix_position [private]
Is the position of the fish back prescribed?
Definition at line 309 of file elastic_poisson.cc.
Referenced by RefineableFishPoissonProblem< ELEMENT >::RefineableFishPoissonProblem().
Load_pt
template<class ELEMENT >
Data* RefineableFishPoissonProblem< ELEMENT >::Load_pt [private]
Pointer to data item that stores the "load" on the fish back.
Definition at line 306 of file elastic_poisson.cc.
Referenced by RefineableFishPoissonProblem< ELEMENT >::load(), and RefineableFishPoissonProblem< ELEMENT >::RefineableFishPoissonProblem().
Trace_file
template<class ELEMENT >
ofstream RefineableFishPoissonProblem< ELEMENT >::Trace_file [private]
Trace file.
Definition at line 296 of file elastic_poisson.cc.
Referenced by RefineableFishPoissonProblem< ELEMENT >::RefineableFishPoissonProblem().
The documentation for this class was generated from the following file:
elastic_poisson.cc